Name = new Array();
Name['Option'] = new Array();
for (i=0;i<=6;i++) Name['Option'][i] = new Array('','','','','','');

Name['Option'][0] = new Array(0,'STA','STA','体力','STA','體力');
Name['Option'][1] = new Array(1,'STR','STR','筋力','STR','力量');
Name['Option'][2] = new Array(2,'AGI','AGI','敏捷','AGI','敏捷');
Name['Option'][3] = new Array(3,'DEX','DEX','器用','DEX','技巧');
Name['Option'][4] = new Array(4,'SPR','SPR','霊感','SPR','靈感');
Name['Option'][5] = new Array(5,'INT','INT','知性','INT','智慧');
Name['Option'][6] = new Array(6,'LP','LP','LP','LP','HP');
Name['Option'][7] = new Array(7,'MP','MP','MP','MP','MP');
Name['Option'][8] = new Array(8,'POT','POT','<span title="ポーション回復量" class="help">POT回復</span>','<span title="Potion recovery increase" class="help">POT</span>','藥劑效果');
Name['Option'][9] = new Array(9,'LPRecSPD','LPRecSPD','<span title="LP自然回復速度" class="help">LP回復速度</span>','<span title="LP recovery speed" class="help">LP Rec SPD</span>','<span title="HP自然恢復速度" class="help">HP恢復速度</span>');
Name['Option'][10] = new Array(10,'MPRecSPD','MPRecSPD','<span title="MP自然回復速度" class="help">MP回復速度</span>','<span title="MP recovery speed" class="help">MP Rec SPD</span>','<span title="MP自然恢復速度" class="help">MP恢復速度</span>');
Name['Option'][11] = new Array(11,'LPSkill','LPSkill','<span title="LP回復スキル効果量" class="help">LPスキル</span>','<span title="%LP Healed" class="help">%LP Heal</span>','<span title="HP恢復技能的效果" class="help">HP技能</span>');
Name['Option'][12] = new Array(12,'LPRec','LPRec','<span title="LP自然回復量" class="help">LP回復量</span>','<span title="LP recovery rate" class="help">LP Recovery</span>','<span title="HP自然恢復量" class="help">HP恢復量</span>');
Name['Option'][13] = new Array(13,'MPRec','MPRec','<span title="MP自然回復量" class="help">MP回復量</span>','<span title="MP Recovery rate" class="help">MP Recovery</span>','<span title="MP自然恢復量" class="help">MP恢復量</span>');
Name['Option'][14] = new Array(14,'LPSit','LPRec','<span title="座っている時のLP回復量" class="help">LP回復量/座</span>','<span title="LP recovery rate (sitting)" class="help">LP Rec sit</span>','<span title="坐在HP恢復量" class="help">HP恢復量/坐</span>');
Name['Option'][15] = new Array(15,'MPSit','MPRec','<span title="座っている時のMP回復量" class="help">MP回復量/座</span>','<span title="MP recovery rate (sitting)" class="help">MP Rec sit</span>','<span title="坐在MP恢復量" class="help">MP恢復量/坐</span>');
Name['Option'][16] = new Array(16,'LPsec','LPsec','<span title="2秒毎のLP回復量" class="help">LP回復量/2s</span>','<span title="The amount of LP restored every 2 seconds" class="help">LP Rec 2sec</span>','<span title="2節HP每秒恢復量" class="help">HP恢復量/2s</span>');
Name['Option'][17] = new Array(17,'MPsec','MPsec','<span title="2秒毎のMP回復量" class="help">MP回復量/2s</span>','<span title="The amount of MP restored every 2 seconds" class="help">MP Rec 2sec</span>','<span title="2節HP每秒恢復量" class="help">MP恢復量/2s</span>');
Name['Option'][18] = new Array(18,'ATK','ATK','攻/最大','MaxATK','攻/最大');
Name['Option'][19] = new Array(19,'ATKFront','ATKFront','<span title="正面からの攻撃力＋" class="help">攻/正面</span>','<span title="ATK / Frontattack" class="help">Front+</span>','<span title="從正面進攻" class="help">攻/前面</span>');
Name['Option'][20] = new Array(20,'ATKBack','ATKBack','<span title="背後からの攻撃力＋" class="help">攻/背後</span>','<span title="ATK / Backattack" class="help">Back+</span>','<span title="從背後攻擊" class="help">攻/後面</span>');
Name['Option'][21] = new Array(21,'WeaDAM','WeaDAM','<span title="武器による物理ダメージ" class="help">武器ダメ</span>','<span title="DAM / Weapon" class="help">Weapon</span>','<span title="物理傷害的武器" class="help">武器傷害</span>');
Name['Option'][22] = new Array(22,'DAMAnimal','DAMAnimal','<span title="動物類へのダメージ" class="help">攻/動物類</span>','<span title="Physical damage to the animal" class="help">Animal D</span>','<span title="損害動物物種" class="help">攻/動物</span>');
Name['Option'][23] = new Array(23,'DAMInsect','DAMInsect','<span title="昆虫類へのダメージ" class="help">攻/昆虫類</span>','<span title="Physical damage to the insect" class="help">Insect D</span>','<span title="昆蟲損害" class="help">攻/昆蟲</span>');
Name['Option'][24] = new Array(24,'DAMReptilian','DAMReptilian','<span title="爬虫類へのダメージ" class="help">攻/爬虫類</span>','<span title="Physical damage to the reptilian" class="help">Reptil D</span>','<span title="損壞的爬行動物" class="help">攻/爬行</span>');
Name['Option'][25] = new Array(25,'DAMDevil','DAMDevil','<span title="悪魔系へのダメージ" class="help">攻/悪魔系</span>','<span title="Physical damage to the devil" class="help">Devil D</span>','<span title="系統損壞魔鬼" class="help">攻/魔鬼</span>');
Name['Option'][26] = new Array(26,'DAMImmortal','DAMImmortal','<span title="不死系へのダメージ" class="help">攻/不死系</span>','<span title="Physical damage to the immortal" class="help">Immort D</span>','<span title="系統損壞亡靈" class="help">攻/亡靈</span>');
Name['Option'][27] = new Array(27,'DAMGhost','DAMGhost','<span title="幽霊系へのダメージ" class="help">攻/幽霊系</span>','<span title="Physical damage to the ghost" class="help">Ghost D</span>','<span title="鬼系統損害" class="help">攻/鬼</span>');
Name['Option'][28] = new Array(28,'DAMInanimate','DAMInanimate','<span title="無生物へのダメージ" class="help">攻/無生物</span>','<span title="Physical damage to the inanimate" class="help">Inanim D</span>','<span title="無生命的損害" class="help">攻/無生命</span>');
Name['Option'][29] = new Array(29,'DAMRiding','DAMRiding','<span title="騎乗キャラクターへのダメージ" class="help">騎乗ダメ</span>','<span title="Damage to the character riding" class="help">Riding D</span>','<span title="損壞的性質騎" class="help">攻/騎兵</span>');
Name['Option'][30] = new Array(30,'DAMKD','DAMKD','<span title="転倒中の相手に対するダメージ" class="help">転倒ダメ</span>','<span title="Knockdown damage" class="help">KDown D</span>','<span title="破壞對手在秋季" class="help">攻/下降</span>');
Name['Option'][31] = new Array(31,'DAMOBJ','DAMOBJ','<span title="オブジェクトへのダメージ" class="help">objダメ</span>','<span title="Object damage" class="help">Objec D</span>','<span title="損害的對象" class="help">攻/對象</span>');
Name['Option'][32] = new Array(32,'DAMMP','DAMMP','<span title="MPダメージ量" class="help">MPダメ</span>','<span title="MP damage" class="help">MP D</span>','MP損害');
Name['Option'][33] = new Array(33,'DAMAura','DAMAura','<span title="オーラダメージ" class="help">オーラ</span>','<span title="Aura damage" class="help">Aura D</span>','損害靈氣');
Name['Option'][34] = new Array(34,'DAMFire','DAMFire','<span title="火炎オーラダメージ" class="help">火炎ダメ</span>','<span title="Fire aura damage" class="help">Fire D</span>','<span title="火屬性靈氣傷害" class="help">靈/火</span>');
Name['Option'][35] = new Array(35,'DAMIce','DAMIce','<span title="冷気オーラダメージ" class="help">冷気ダメ</span>','<span title="Ice aura damage" class="help">Ice D</span>','<span title="冰屬性靈氣傷害" class="help">靈/冰</span>');
Name['Option'][36] = new Array(36,'DAMLightning','DAMLightning','<span title="電撃オーラダメージ" class="help">電撃ダメ</span>','<span title="Lightning aura damage" class="help">Thunder D</span>','<span title="雷屬性靈氣傷害" class="help">靈/雷</span>');
Name['Option'][37] = new Array(37,'DAMPoison','DAMPoison','<span title="毒オーラダメージ" class="help">毒ダメ</span>','<span title="Poison aura damage" class="help">Poison D</span>','<span title="毒屬性靈氣傷害" class="help">靈/毒</span>');
Name['Option'][38] = new Array(38,'DAMLight','DAMLight','<span title="光オーラダメージ" class="help">光ダメ</span>','<span title="Light aura damage" class="help">Light D</span>','<span title="光屬性靈氣傷害" class="help">靈/光</span>');
Name['Option'][39] = new Array(39,'DAMDark','DAMDark','<span title="闇オーラダメージ" class="help">闇ダメ</span>','<span title="Darkness aura damage" class="help">Dark D</span>','<span title="黑暗屬性靈氣傷害" class="help">靈/黑暗</span>');
Name['Option'][40] = new Array(40,'RangeMelee','RangeMelee','<span title="近接武器の射程" class="help">射程/近</span>','<span title="Range of melee weapons" class="help">Melee</span>','<span title="近戰武器範圍" class="help">範/近戰</span>');
Name['Option'][41] = new Array(41,'RangeRange','RangeRange','<span title="遠距離武器の射程" class="help">射程/遠</span>','<span title="Ranged weapon range" class="help">Range</span>','<span title="遠程武器射程" class="help">範/遠程</span>');
Name['Option'][42] = new Array(42,'MATK','MATK','<span title="魔法攻撃力" class="help">魔攻</span>','<span title="Magic attack" class="help">MATK</span>','<span title="魔法攻擊" class="help">魔攻</span>');
Name['Option'][43] = new Array(43,'MATKFire','MATKFire','<span title="火炎属性魔法攻撃力＋" class="help">魔/火炎</span>','<span title="Fire element skill damage" class="help">Fire MA</span>','<span title="火屬性攻擊魔法" class="help">魔/火</span>');
Name['Option'][44] = new Array(44,'MATKIce','MATKIce','<span title="冷気属性魔法攻撃力＋" class="help">魔/冷気</span>','<span title="Ice element skill damage" class="help">Ice MA</span>','<span title="冰屬性攻擊魔法" class="help">魔/冰</span>');
Name['Option'][45] = new Array(45,'MATKLightning','MATKLightning','<span title="電撃属性魔法攻撃力＋" class="help">魔/電撃</span>','<span title="Lightning element skill damage" class="help">Thunder MA</span>','<span title="雷屬性攻擊魔法" class="help">魔/雷</span>');
Name['Option'][46] = new Array(46,'MATKPoison','MATKPoison','<span title="毒属性魔法攻撃力＋" class="help">魔/毒</span>','<span title="Poison element skill damage" class="help">Poison MA</span>','<span title="毒屬性攻擊魔法" class="help">魔/毒</span>');
Name['Option'][47] = new Array(47,'MATKLight','MATKLight','<span title="光属性魔法攻撃力＋" class="help">魔/光</span>','<span title="Light element skill damage" class="help">Light MA</span>','<span title="光屬性攻擊魔法" class="help">魔/光</span>');
Name['Option'][48] = new Array(48,'MATKDark','MATKDark','<span title="闇属性魔法攻撃力＋" class="help">魔/闇</span>','<span title="Darkness element skill damage" class="help">Dark MA</span>','<span title="黑暗屬性攻擊魔法" class="help">魔/黑暗</span>');
Name['Option'][49] = new Array(49,'DEF','DEF','防御力','DEF','防禦');
Name['Option'][50] = new Array(50,'RESFront','RESFront','<span title="正面からの物理ダメージ" class="help">正面ダメ</span>','<span title="Frontattack damage resist" class="help">R/Front</span>','<span title="從前面物理傷害" class="help">防/前面</span>');
Name['Option'][51] = new Array(51,'RESBack','RESBack','<span title="背後からの物理ダメージ" class="help">背後ダメ</span>','<span title="Backattack damage resist" class="help">R/Back</span>','<span title="從後面物理傷害" class="help">防/後面</span>');
Name['Option'][52] = new Array(52,'RESPhyDAM','RESPhyDAM','<span title="被物理ダメージ" class="help">被物ダメ</span>','<span title="Physical damage resist" class="help">Phy RES</span>','物理傷害');
Name['Option'][53] = new Array(53,'RESAnimal','RESAnimal','<span title="動物類からの物理ダメージ軽減率" class="help">防/動物類</span>','<span title="Physical damage from the animal" class="help">Animal RES</span>','<span title="從動物的物理傷害減少" class="help">防/動物</span>');
Name['Option'][54] = new Array(54,'RESInsect','RESInsect','<span title="昆虫類からの物理ダメージ軽減率" class="help">防/昆虫類</span>','<span title="Physical damage from the insect" class="help">Insect RES</span>','<span title="從昆蟲的物理傷害減少" class="help">防/昆蟲</span>');
Name['Option'][55] = new Array(55,'RESReptilian','RESReptilian','<span title="爬虫類からの物理ダメージ軽減率" class="help">防/爬虫類</span>','<span title="Physical damage from the reptilian" class="help">Reptilia RES</span>','<span title="從爬蟲類的物理傷害減少" class="help">防/爬蟲</span>');
Name['Option'][56] = new Array(56,'RESDevil','RESDevil','<span title="悪魔系からの物理ダメージ軽減率" class="help">防/悪魔系</span>','<span title="Physical damage from the devil" class="help">Devil RES</span>','<span title="從魔鬼的物理傷害減少" class="help">防/魔鬼</span>');
Name['Option'][57] = new Array(57,'RESImmortal','RESImmortal','<span title="不死系からの物理ダメージ軽減率" class="help">防/不死系</span>','<span title="Physical damage from the immortal" class="help">Immortal RES</span>','<span title="從不朽的物理傷害減少" class="help">防/不朽</span>');
Name['Option'][58] = new Array(58,'RESGhost','RESGhost','<span title="幽霊系からの物理ダメージ軽減率" class="help">防/幽霊系</span>','<span title="Physical damage from the ghost" class="help">Ghost RES</span>','<span title="從鬼命的物理傷害減少" class="help">防/鬼</span>');
Name['Option'][59] = new Array(59,'RESInanimate','RESInanimate','<span title="無生物からの物理ダメージ軽減率" class="help">防/無生物</span>','<span title="Physical damage from the inanimate" class="help">Inanimat RES</span>','<span title="從無生命的物理傷害減少" class="help">防/無生命</span>');
Name['Option'][60] = new Array(60,'RESMagDAM','RESMagDAM','<span title="被魔法ダメージ" class="help">被魔ダメ</span>','<span title="Magical damage resist" class="help">Mag RES</span>','魔法傷害');
Name['Option'][61] = new Array(61,'DAMCut','DAMCut','<span title="ダメージカット" class="help">ダメカット</span>','<span title="Damage cut rate" class="help">DAMCut</span>','切割損傷');
Name['Option'][62] = new Array(62,'ACC','ACC','命中','Accuracy','命中');
Name['Option'][63] = new Array(63,'ACCFront','ACC','<span title="正面から攻撃した時の命中" class="help">命/正面</span>','<span title="ACC / Frontattack" class="help">Ac/Front</span>','<span title="當從正面攻擊命中" class="help">命/前面</span>');
Name['Option'][64] = new Array(64,'ACCBack','ACC','<span title="背後から攻撃した時の命中" class="help">命/背後</span>','<span title="ACC / Backattack" class="help">Ac/Back</span>','<span title="當攻擊從後面撞上" class="help">命/後面</span>');
Name['Option'][65] = new Array(65,'Dodge','Dodge','回避','Dodge','迴避');
Name['Option'][66] = new Array(66,'EVAMelee','EVAMelee','<span title="近接物理攻撃回避率" class="help">避/物理</span>','<span title="Melee evasion" class="help">Mel EVA</span>','<span title="近戰迴避" class="help">迴/近戰</span>');
Name['Option'][67] = new Array(67,'EVARange','EVARange','<span title="遠距離攻撃回避率" class="help">避/遠</span>','<span title="Ranged evasion" class="help">Ran EVA</span>','<span title="遠程迴避" class="help">迴/遠程</span>');
Name['Option'][68] = new Array(68,'EVAMagic','EVAMagic','<span title="魔法攻撃回避率" class="help">避/魔法</span>','<span title="Magic evasion" class="help">Mag EVA</span>','<span title="魔法攻擊迴避" class="help">迴/魔法</span>');
Name['Option'][69] = new Array(69,'Cri','Cri','<span title="クリティカル発生率" class="help">Cri率</span>','<span title="Critical hit rate" class="help">Cri</span>','<span title=" " class="help">暴擊率</span>');
Name['Option'][70] = new Array(70,'CriRES','CriRES','<span title="被クリティカル発生率" class="help">被Cri率</span>','<span title="Critical resist" class="help">Cri RES</span>','<span title="防/暴擊率" class="help">防/暴擊</span>');
Name['Option'][71] = new Array(71,'CriDAM','CriDAM','<span title="クリティカルダメージ" class="help">CriDAM</span>','<span title="Critical damage" class="help">Cri DAM</span>','<span title="暴擊威力" class="help">暴擊威力</span>');
Name['Option'][72] = new Array(72,'CriDAMRES','CriDAMRES','<span title="被クリティカルダメージ軽減率" class="help">被CriDAM</span>','<span title="Critical damage resist" class="help">CDAM RES</span>','<span title="防/暴擊威力" class="help">防/暴威</span>');
Name['Option'][73] = new Array(73,'ATKSPD','ATKSPD','攻撃速度','<span title="Attack speed" class="help">ATK SPD</span>','攻擊速度');
Name['Option'][74] = new Array(74,'MoveSPD','MoveSPD','移動速度','<span title="Moving speed" class="help">Move SPD</span>','行走速度');
Name['Option'][75] = new Array(75,'MoveSPD2','MoveSPD','<span title="街での移動速度" class="help">街/移動</span>','<span title="Moving speed in the city" class="help">TownMSP</span>','<span title="速度變化的城市" class="help">市/行走</span>');
Name['Option'][76] = new Array(76,'ReduceMP','ReduceMP','消費MP','<span title="Reduce MP" class="help">Red MP</span>','消耗MP');
Name['Option'][77] = new Array(77,'CastSPD','CastSPD','詠唱速度','<span title="Casting speed" class="help">Cast SPD</span>','詠唱速度');
Name['Option'][78] = new Array(78,'CastTime','CastSPD','詠唱時間','<span title="Casting time" class="help">CastTime</span>','詠唱時間');
Name['Option'][79] = new Array(79,'Cooldown','Cooldown','<span title="再使用時間" class="help">再使用</span>','Cooldown','冷卻時間');
Name['Option'][80] = new Array(80,'Gdebuff','Gdebuff','<span title="与debuff持続時間" class="help">与debuff</span>','<span title="Given duration debuff" class="help">G debuff</span>','<span title="該法術的持續時間減弱" class="help">法術持續</span>');
Name['Option'][81] = new Array(81,'RelHorse','RelHorse','<span title="騎乗時のステータス開放率" class="help">騎乗ステ</span>','<span title="Release rate status on horseback" class="help">Re Horse</span>','<span title="釋放率騎馬狀態" class="help">釋放騎馬</span>');
Name['Option'][82] = new Array(82,'EXP','EXP','<span title="獲得EXP＋" class="help">EXP+</span>','EXP+','EXP+');
Name['Option'][83] = new Array(83,'SkillEXP','SkillEXP','<span title="熟練度増加量" class="help">熟練度</span>','Skill+','熟練+');
Name['Option'][84] = new Array(84,'DPenalty','DPenalty','<span title="デスペナルティー" class="help">デスペナ</span>','<span title="Death Penalty" class="help">Penalty</span>','在死亡');
Name['Option'][85] = new Array(85,'RatePurler','RatePurler','<span title="落馬発生確率" class="help">攻/落馬</span>','<span title="Purler rate" class="help">Purler</span>','<span title="概率從馬背上掉下" class="help">攻/從馬</span>');
Name['Option'][86] = new Array(86,'RateKB','RateKB','<span title="ノックバック発生確率" class="help">攻/KB</span>','<span title="Knockback rate" class="help">KB rate</span>','<span title="擊退的發生率" class="help">攻/擊退</span>');
Name['Option'][87] = new Array(87,'RatePenalty','RatePenalty','<span title="罰発生確率" class="help">攻/罰</span>','<span title="Penalty rate" class="help">Penalty</span>','<span title="罰的發生率" class="help">攻/罰</span>');
Name['Option'][88] = new Array(88,'RateStasis','RateStasis','<span title="タイムステイシス発生確率" class="help">攻/タイム</span>','<span title="Stasis rate" class="help">Stasis</span>','<span title="思考凝結的發生率" class="help">攻/思考</span>');
Name['Option'][89] = new Array(89,'RateBurnF','RateBurn','<span title="火傷発生確率 (弱)" class="help">攻/火傷 弱</span>','<span title="Burn rate [feeble]" class="help">Burn[F]</span>','<span title="燒傷的發生率 (弱)" class="help">攻/燒傷 弱</span>');
Name['Option'][90] = new Array(90,'RateBurnI','RateBurn','<span title="火傷発生確率 (強)" class="help">攻/火傷 強</span>','<span title="Burn rate [intense]" class="help">Burn[I]</span>','<span title="燒傷的發生率 (強)" class="help">攻/燒傷 強</span>');
Name['Option'][91] = new Array(91,'RateStunF','RateStun','<span title="気絶発生確率 (弱)" class="help">攻/気絶 弱</span>','<span title="Stun rate [feeble]" class="help">Stun[F]</span>','<span title="暈眩的發生率 (弱)" class="help">攻/暈眩 弱</span>');
Name['Option'][92] = new Array(92,'RateStunI','RateStun','<span title="気絶発生確率 (強)" class="help">攻/気絶 強</span>','<span title="Stun rate [intense]" class="help">Stun[I]</span>','<span title="暈眩的發生率 (強)" class="help">攻/暈眩 強</span>');
Name['Option'][93] = new Array(93,'RateFrozenF','RateFrozen','<span title="凍傷発生確率 (弱)" class="help">攻/凍傷 弱</span>','<span title="Frozen rate [feeble]" class="help">Frozen[F]</span>','<span title="凍傷的發生率 (弱)" class="help">攻/凍傷 弱</span>');
Name['Option'][94] = new Array(94,'RateFrozenI','RateFrozen','<span title="凍傷発生確率 (強)" class="help">攻/凍傷 強</span>','<span title="Frozen rate [intense]" class="help">Frozen[I]</span>','<span title="凍傷的發生率 (強)" class="help">攻/凍傷 強</span>');
Name['Option'][95] = new Array(95,'RateKDF','RateKD','<span title="転倒発生確率 (弱)" class="help">攻/転倒 弱</span>','<span title="Knockdown rate [feeble]" class="help">KDown[F]</span>','<span title="擊倒的發生率 (弱)" class="help">攻/擊倒 弱</span>');
Name['Option'][96] = new Array(96,'RateKDI','RateKD','<span title="転倒発生確率 (強)" class="help">攻/転倒 強</span>','<span title="Knockdown rate [intense]" class="help">KDown[I]</span>','<span title="擊倒的發生率 (強)" class="help">攻/擊倒 強</span>');
Name['Option'][97] = new Array(97,'RatePoisonF','RatePoison','<span title="毒発生確率 (弱)" class="help">攻/毒 弱</span>','<span title="Poison rate [feeble]" class="help">Poison[F]</span>','<span title="中毒的發生率 (弱)" class="help">攻/中毒 弱</span>');
Name['Option'][98] = new Array(98,'RatePoisonI','RatePoison','<span title="毒発生確率 (強)" class="help">攻/毒 強</span>','<span title="Poison rate [intense]" class="help">Poison[I]</span>','<span title="中毒的發生率 (強)" class="help">攻/中毒 強</span>');
Name['Option'][99] = new Array(99,'RateBleedingF','RateBleeding','<span title="出血発生確率 (弱)" class="help">攻/出血 弱</span>','<span title="Bleeding rate [feeble]" class="help">Bleeding[F]</span>','<span title="出血的發生率 (弱)" class="help">攻/出血 弱</span>');
Name['Option'][100] = new Array(100,'RateBleedingI','RateBleeding','<span title="出血発生確率 (強)" class="help">攻/出血 強</span>','<span title="Bleeding rate [intense]" class="help">Bleeding[I]</span>','<span title="出血的發生率 (強)" class="help">攻/出血 強</span>');
Name['Option'][101] = new Array(101,'RateImmobileF','RateImmobile','<span title="移動不可発生確率 (弱)" class="help">攻/不可 弱</span>','<span title="Immobile rate [feeble]" class="help">Immobile[F]</span>','<span title="他們不能走的發生率 (弱)" class="help">攻/不走 弱</span>');
Name['Option'][102] = new Array(102,'RateImmobileI','RateImmobile','<span title="移動不可発生確率 (強)" class="help">攻/不可 強</span>','<span title="Immobile rate [intense]" class="help">Immobile[I]</span>','<span title="他們不能走的發生率 (強)" class="help">攻/不走 強</span>');
Name['Option'][103] = new Array(103,'RateSleepF','RateSleep','<span title="睡眠発生確率 (弱)" class="help">攻/睡眠 弱</span>','<span title="Sleep rate [feeble]" class="help">Sleep[F]</span>','<span title="睡眠的發生率 (弱)" class="help">攻/睡眠 弱</span>');
Name['Option'][104] = new Array(104,'RateSleepI','RateSleep','<span title="睡眠発生確率 (強)" class="help">攻/睡眠 強</span>','<span title="Sleep rate [intense]" class="help">Sleep[I]</span>','<span title="睡眠的發生率 (強)" class="help">攻/睡眠 強</span>');
Name['Option'][105] = new Array(105,'RateMadF','RateMad','<span title="乱心発生確率 (弱)" class="help">攻/乱心 弱</span>','<span title="Madness rate [feeble]" class="help">Madness[F]</span>','<span title="錯亂發生率 (弱)" class="help">攻/錯亂 弱</span>');
Name['Option'][106] = new Array(106,'RateMadI','RateMad','<span title="乱心発生確率 (強)" class="help">攻/乱心 強</span>','<span title="Madness rate [intense]" class="help">Madness[I]</span>','<span title="錯亂發生率 (強)" class="help">攻/錯亂 強</span>');
Name['Option'][107] = new Array(107,'RateSilenceF','RateSilence','<span title="沈黙発生確率 (弱)" class="help">攻/沈黙 弱</span>','<span title="Silence rate [feeble]" class="help">Silence[F]</span>','<span title="沉默的發生率 (弱)" class="help">攻/沉默 弱</span>');
Name['Option'][108] = new Array(108,'RateSilenceI','RateSilence','<span title="沈黙発生確率 (強)" class="help">攻/沈黙 強</span>','<span title="Silence rate [intense]" class="help">Silence[I]</span>','<span title="沉默的發生率 (強)" class="help">攻/沉默 強</span>');
Name['Option'][109] = new Array(109,'RateWeakF','RateWeak','<span title="衰弱発生確率 (弱)" class="help">攻/衰弱 弱</span>','<span title="Weakening rate [feeble]" class="help">Weak[F]</span>','<span title="弱點發生率 (弱)" class="help">攻/弱點 弱</span>');
Name['Option'][110] = new Array(110,'RateWeakI','RateWeak','<span title="衰弱発生確率 (強)" class="help">攻/衰弱 強</span>','<span title="Weakening rate [intense]" class="help">Weak[I]</span>','<span title="弱點發生率 (強)" class="help">攻/弱點 強</span>');
Name['Option'][111] = new Array(111,'RateDiseaseF','RateDisease','<span title="病気発生確率 (弱)" class="help">攻/病気 弱</span>','<span title="Disease rate [feeble]" class="help">Disease[F]</span>','<span title="疾病發生率 (弱)" class="help">攻/疾病 弱</span>');
Name['Option'][112] = new Array(112,'RateDiseaseI','RateDisease','<span title="病気発生確率 (強)" class="help">攻/病気 強</span>','<span title="Disease rate [intense]" class="help">Disease[I]</span>','<span title="疾病發生率 (強)" class="help">攻/疾病 強</span>');
Name['Option'][113] = new Array(113,'RateCurseF','RateCurse','<span title="呪い発生確率 (弱)" class="help">攻/呪い 弱</span>','<span title="Curse rate [feeble]" class="help">Curse[F]</span>','<span title="詛咒發生率 (弱)" class="help">攻/詛咒 弱</span>');
Name['Option'][114] = new Array(114,'RateCurseI','RateCurse','<span title="呪い発生確率 (強)" class="help">攻/呪い 強</span>','<span title="Curse rate [intense]" class="help">Curse[I]</span>','<span title="詛咒發生率 (強)" class="help">攻/詛咒 強</span>');
Name['Option'][115] = new Array(115,'RateCorrosionF','RateCorrosion','<span title="腐食発生確率 (弱)" class="help">攻/腐食 弱</span>','<span title="Corrosion rate [feeble]" class="help">Corros[F]</span>','<span title="腐蝕發生率 (弱)" class="help">攻/腐蝕 弱</span>');
Name['Option'][116] = new Array(116,'RateCorrosionI','RateCorrosion','<span title="腐食発生確率 (強)" class="help">攻/腐食 強</span>','<span title="Corrosion rate [intense]" class="help">Corros[I]</span>','<span title="腐蝕發生率 (強)" class="help">攻/腐蝕 強</span>');
Name['Option'][117] = new Array(117,'RateCastDelayF','RateCastDelay','<span title="詠唱遅延発生確率 (弱)" class="help">攻/詠唱 弱</span>','<span title="Casting Delay rate [feeble]" class="help">CDelay[F]</span>','<span title="施法速度延遲發生率 (弱)" class="help">攻/延遲 弱</span>');
Name['Option'][118] = new Array(118,'RateCastDelayI','RateCastDelay','<span title="詠唱遅延発生確率 (強)" class="help">攻/詠唱 強</span>','<span title="Casting Delay rate [intense]" class="help">CDelay[I]</span>','<span title="施法速度延遲發生率 (強)" class="help">攻/延遲 強</span>');
Name['Option'][119] = new Array(119,'RateLPF','RateLP','<span title="最大LP減少発生確率 (弱)" class="help">攻/LP減 弱</span>','<span title="Reduced LP [feeble]" class="help">Red LP[F]</span>','<span title="最大HP減少 (弱)" class="help">攻/HP減 弱</span>');
Name['Option'][120] = new Array(120,'RateLPI','RateLP','<span title="最大LP減少発生確率 (強)" class="help">攻/LP減 強</span>','<span title="Reduced LP [intense]" class="help">Red LP[I]</span>','<span title="最大HP減少 (強)" class="help">攻/HP減 強</span>');
Name['Option'][121] = new Array(121,'RateATKF','RateATK','<span title="攻撃力減少発生確率 (弱)" class="help">攻/攻減 弱</span>','<span title="Reduced ATK power [feeble]" class="help">Red ATK[F]</span>','<span title="攻擊力減少 (弱)" class="help">攻/攻減 弱</span>');
Name['Option'][122] = new Array(122,'RateATKI','RateATK','<span title="攻撃力減少発生確率 (強)" class="help">攻/攻減 強</span>','<span title="Reduced ATK power [intense]" class="help">Red ATK[I]</span>','<span title="攻擊力減少 (強)" class="help">攻/攻減 強</span>');
Name['Option'][123] = new Array(123,'RateDEFF','RateDEF','<span title="防御力低下発生確率 (弱)" class="help">攻/防減 弱</span>','<span title="Reduced Defense [feeble]" class="help">Red DEF[F]</span>','<span title="防禦力減少 (弱)" class="help">攻/防減 弱</span>');
Name['Option'][124] = new Array(124,'RateDEFI','RateDEF','<span title="防御力低下発生確率 (強)" class="help">攻/防減 強</span>','<span title="Reduced Defense [intense]" class="help">Red DEF[I]</span>','<span title="防禦力減少 (強)" class="help">攻/防減 強</span>');
Name['Option'][125] = new Array(125,'RateACCF','RateACC','<span title="命中力低下発生確率 (弱)" class="help">攻/命減 弱</span>','<span title="Reduced ACC [feeble]" class="help">Red ACC[F]</span>','<span title="命中減少 (弱)" class="help">攻/命減 弱</span>');
Name['Option'][126] = new Array(126,'RateACCI','RateACC','<span title="命中力低下発生確率 (強)" class="help">攻/命減 強</span>','<span title="Reduced ACC [intense]" class="help">Red ACC[I]</span>','<span title="命中減少 (強)" class="help">攻/命減 強</span>');
Name['Option'][127] = new Array(127,'RateEVAF','RateEVA','<span title="回避減少発生確率 (弱)" class="help">攻/回減 弱</span>','<span title="Decreased Dodge [feeble]" class="help">Red EVA[F]</span>','<span title="迴避減少 (弱)" class="help">攻/迴減 弱</span>');
Name['Option'][128] = new Array(128,'RateEVAI','RateEVA','<span title="回避減少発生確率 (強)" class="help">攻/回減 強</span>','<span title="Decreased Dodge [intense]" class="help">Red EVA[I]</span>','<span title="迴避減少 (強)" class="help">攻/迴減 強</span>');
Name['Option'][129] = new Array(129,'RateSlowMoveF','RateSlowMove','<span title="移動速度減少発生確率 (弱)" class="help">攻/移動 弱</span>','<span title="Slow Move rate [feeble]" class="help">SMove[F]</span>','<span title="步行速度降低的發生率 (弱)" class="help">攻/步行 弱</span>');
Name['Option'][130] = new Array(130,'RateSlowMoveI','RateSlowMove','<span title="移動速度減少発生確率 (強)" class="help">攻/移動 強</span>','<span title="Slow Move rate [intense]" class="help">SMove[I]</span>','<span title="步行速度降低的發生率 (強)" class="help">攻/步行 強</span>');
Name['Option'][131] = new Array(131,'RateProvokedF','RateProvoked','<span title="挑発発生確率 (弱)" class="help">攻/挑発 弱</span>','<span title="Provoked [feeble]" class="help">Provoke[F]</span>','<span title="挑釁 (弱)" class="help">攻/挑釁 弱</span>');
Name['Option'][132] = new Array(132,'RateProvokedI','RateProvoked','<span title="挑発発生確率 (強)" class="help">攻/挑発 強</span>','<span title="Provoked [intense]" class="help">Provoke[I]</span>','<span title="挑釁 (強)" class="help">攻/挑釁 強</span>');
Name['Option'][133] = new Array(133,'Blocking','Blocking','<span title="ブロッキング解除耐性" class="help">ブロッキング</span>','<span title="De-blocking immunity" class="help">De-blocking</span>','德阻斷免疫');
Name['Option'][134] = new Array(134,'RESCast','RESCast','詠唱妨害耐性','<span title="Cast cancel resist" class="help">Cast RES</span>','吟詠取消抗性');
Name['Option'][135] = new Array(135,'Reflection','Reflection','<span title="近接物理ダメージ反射率" class="help">反射</span>','<span title="Physical damage reflection" class="help">Reflect</span>','反射近戰傷害');
Name['Option'][136] = new Array(136,'DReflect','DReflect','<span title="Debuff反射確率" class="help">Debuff反射</span>','<span title="Debuff reflection probability" class="help">D-Reflect</span>','<span title="debuff的反射率" class="help">debuff反射</span>');
Name['Option'][137] = new Array(137,'RESDAura','RESDAura','<span title="闇オーラの反動ダメージ" class="help">闇反動</span>','<span title="Darkness aura recoil damage" class="help">DAura RES</span>','<span title="黑暗屬性靈氣反沖損害" class="help">黑暗反沖</span>');
Name['Option'][138] = new Array(138,'RESFire','RESFire','火炎耐性','<span title="Fire resist" class="help">Fire R</span>','火抗性');
Name['Option'][139] = new Array(139,'RESIce','RESIce','冷気耐性','<span title="Ice resist" class="help">Ice R</span>','冰抗性');
Name['Option'][140] = new Array(140,'RESLightning','RESLightning','電撃耐性','<span title="Lightning resist" class="help">Thund R</span>','雷抗性');
Name['Option'][141] = new Array(141,'RESPoison','RESPoison','毒耐性','<span title="Poison resist" class="help">Poiso R</span>','毒抗性');
Name['Option'][142] = new Array(142,'RESCharm','RESCharm','魅了耐性','<span title="Charm resist" class="help">Charm R</span>','魅惑抗性');
Name['Option'][143] = new Array(143,'RESLight','RESLight','光耐性','<span title="Light resist" class="help">Light R</span>','光抗性');
Name['Option'][144] = new Array(144,'RESDark','RESDark','闇耐性','<span title="Darkness resist" class="help">Dark R</span>','黑暗抗性');
Name['Option'][145] = new Array(145,'RESMagic','RESMagic','魔術耐性','<span title="Magic resist" class="help">Magic R</span>','秘法抗性');
Name['Option'][146] = new Array(146,'RESPDebuff','RESPDebuff','<span title="火傷、気絶、凍傷、転倒、毒、出血、移動不可耐性" class="help">身体異常</span>','<span title="Physical De-buff resist" class="help">PDe-B R</span>','<span title="異常體抗性" class="help">體抗性</span>');
Name['Option'][147] = new Array(147,'RESMDebuff','RESMDebuff','<span title="睡眠、乱心、沈黙、呪い、衰弱、病気、詠唱遅延、腐食耐性" class="help">精神異常</span>','<span title="Mental De-buff resist" class="help">MDe-B R</span>','<span title="精神錯亂抗性" class="help">精神抗性</span>');
Name['Option'][148] = new Array(148,'RESBurn','RESBurn','火傷耐性','<span title="Burn resist" class="help">Burn RES</span>','燒傷抗性');
Name['Option'][149] = new Array(149,'RESStun','RESStun','気絶耐性','<span title="Stun resist" class="help">Stun RES</span>','暈眩抗性');
Name['Option'][150] = new Array(150,'RESFrozen','RESFrozen','凍傷耐性','<span title="Frozen resist" class="help">Frozen RES</span>','凍傷抗性');
Name['Option'][151] = new Array(151,'RESKD','RESKD','転倒耐性','<span title="Knockdown resist" class="help">KD RES</span>','擊倒抗性');
Name['Option'][152] = new Array(152,'RESPurler','RESPurler','落馬耐性','<span title="Purler resist" class="help">Purler RES</span>','<span title="從馬背下跌抗性" class="help">從馬背下跌</span>');
Name['Option'][153] = new Array(153,'RESKB','RESKB','<span title="ノックバック耐性" class="help">KB耐性</span>','<span title="Knockback resist" class="help">KB RES</span>','擊退抗性');
Name['Option'][154] = new Array(154,'RESBleeding','RESBleeding','出血耐性','<span title="Bleeding resist" class="help">Bleeding RES</span>','出血抗性');
Name['Option'][155] = new Array(155,'RESImmobile','RESImmobile','移動不可耐性','<span title="Immobile resist" class="help">Immobile RES</span>','<span title="步行速度降低抗性" class="help">步行速度降低</span>');
Name['Option'][156] = new Array(156,'RESSleep','RESSleep','睡眠耐性','<span title="Sleep resist" class="help">Sleep RES</span>','睡眠抗性');
Name['Option'][157] = new Array(157,'RESMadness','RESMadness','乱心耐性','<span title="Madness resist" class="help">Madness RES</span>','錯亂抗性');
Name['Option'][158] = new Array(158,'RESSilence','RESSilence','沈黙耐性','<span title="Silence resist" class="help">Silence RES</span>','沉默抗性');
Name['Option'][159] = new Array(159,'RESCurse','RESCurse','呪い耐性','<span title="Curse resist" class="help">Curse RES</span>','詛咒抗性');
Name['Option'][160] = new Array(160,'RESWeakening','RESWeakening','衰弱耐性','<span title="Weakening resist" class="help">Weak RES</span>','弱點抗性');
Name['Option'][161] = new Array(161,'RESDisease','RESDisease','病気耐性','<span title="Disease resist" class="help">Disease RES</span>','疾病抗性');
Name['Option'][162] = new Array(162,'RESDebuff','RESDebuff','<span title="被Debuff持続時間" class="help">被debuff</span>','<span title="Debuff duration" class="help">Debuff RES</span>','<span title="debuff的持續時間" class="help">debuff持續</span>');
Name['Option'][163] = new Array(163,'PhBurn','RESBurn','<span title="火傷の耐性段階" class="help">火傷段階</span>','<span title="Burn phase resist" class="help">Burn Ph</span>','<span title="級抗性燒傷" class="help">燒傷/級</span>');
Name['Option'][164] = new Array(164,'PhStun','RESStun','<span title="気絶の耐性段階" class="help">気絶段階</span>','<span title="Stun phase resist" class="help">Stun Ph</span>','<span title="級抗性暈眩" class="help">暈眩/級</span>');
Name['Option'][165] = new Array(165,'PhFrozen','RESFrozen','<span title="凍傷の耐性段階" class="help">凍傷段階</span>','<span title="Frozen phase resist" class="help">Frozen Ph</span>','<span title="級抗性凍傷" class="help">凍傷/級</span>');
Name['Option'][166] = new Array(166,'PhKD','RESKD','<span title="転倒の耐性段階" class="help">転倒段階</span>','<span title="Knockdown phase resist" class="help">KD Ph</span>','<span title="級抗性擊倒" class="help">擊倒/級</span>');
Name['Option'][167] = new Array(167,'PhPurler','RESPurler','<span title="落馬の耐性段階" class="help">落馬段階</span>','<span title="Purler phase resist" class="help">Purler Ph</span>','<span title="級抗性從馬背下跌" class="help">從馬背/級</span>');
Name['Option'][168] = new Array(168,'PhKB','RESKB','<span title="ノックバックの耐性段階" class="help">KB段階</span>','<span title="Knockback phase resist" class="help">KB Ph</span>','<span title="級抗性擊退" class="help">擊退/級</span>');
Name['Option'][169] = new Array(169,'PhPoision','RESPoison','<span title="毒の耐性段階" class="help">毒段階</span>','<span title="Poison phase resist" class="help">Poison Ph</span>','<span title="級抗性毒" class="help">毒/級</span>');
Name['Option'][170] = new Array(170,'PhBleeding','RESBleeding','<span title="出血の耐性段階" class="help">出血段階</span>','<span title="Bleeding phase resist" class="help">Bleeding Ph</span>','<span title="級抗性出血" class="help">出血/級</span>');
Name['Option'][171] = new Array(171,'PhImmobile','RESImmobile','<span title="移動不可の耐性段階" class="help">移動不可段階</span>','<span title="Immobile phase resist" class="help">Immobile Ph</span>','<span title="級抗性步行速度降低" class="help">步行速度/級</span>');
Name['Option'][172] = new Array(172,'PhSleep','RESSleep','<span title="睡眠の耐性段階" class="help">睡眠段階</span>','<span title="Sleep phase resist" class="help">Sleep Ph</span>','<span title="級抗性睡眠" class="help">睡眠/級</span>');
Name['Option'][173] = new Array(173,'PhMadness','RESMadness','<span title="乱心の耐性段階" class="help">乱心段階</span>','<span title="Madness phase resist" class="help">Madness Ph</span>','<span title="級抗性錯亂" class="help">錯亂/級</span>');
Name['Option'][174] = new Array(174,'PhSilence','RESSilence','<span title="沈黙の耐性段階" class="help">沈黙段階</span>','<span title="Silence phase resist" class="help">Silence Ph</span>','<span title="級抗性沉默" class="help">沉默/級</span>');
Name['Option'][175] = new Array(175,'PhCurse','RESCurse','<span title="呪いの耐性段階" class="help">呪い段階</span>','<span title="Curse phase resist" class="help">Curse Ph</span>','<span title="級抗性詛咒" class="help">詛咒/級</span>');
Name['Option'][176] = new Array(176,'PhWeakening','RESWeakening','<span title="衰弱の耐性段階" class="help">衰弱段階</span>','<span title="Weakening phase resist" class="help">Weak Ph</span>','<span title="級抗性弱點" class="help">弱點/級</span>');
Name['Option'][177] = new Array(177,'PhDisease','RESDisease','<span title="病気の耐性段階" class="help">病気段階</span>','<span title="Disease phase resist" class="help">Disease Ph</span>','<span title="級抗性疾病" class="help">疾病/級</span>');
Name['Option'][178] = new Array(178,'PhCastDelay','RESCastDelay','<span title="詠唱遅延の耐性段階" class="help">詠唱遅延段階</span>','<span title="Casting Delay phase resist" class="help">CDelay Ph</span>','<span title="級抗性施法延遲" class="help">施法延遲/級</span>');
Name['Option'][179] = new Array(179,'PhCorrosion','RESCorrosion','<span title="腐食の耐性段階" class="help">腐食段階</span>','<span title="Corrosion phase resist" class="help">Corr Ph</span>','<span title="級抗性腐蝕" class="help">腐蝕/級</span>');
Name['Option'][180] = new Array(180,'RateMuscle','RateMuscle','<span title="脚力低下発生率" class="help">攻/脚力</span>','<span title="Decreased muscle" class="help">DMuscle</span>','肌肉下降');
Name['Option'][181] = new Array(181,'RateDebuff','RateDebuff','<span title="与debuff成功率" class="help">与debuff率</span>','<span title="debuff success rate" class="help">debuff rate</span>','<span title="debuff的成功率" class="help">debuff率</span>');
Name['Option'][182] = new Array(182,'Disabling','Disabling','<span title="物理ダメージ無効化確率" class="help">物理無効</span>','<span title="Disabling the probability of physical damage" class="help">DP damage</span>','<span title="中和物理傷害機率" class="help">物理中和</span>');
Name['Option'][183] = new Array(183,'DResist','DResist','耐性値減少','<span title="Decrease the resistance" class="help">DResist</span>','<span title="抗生素的下降" class="help">抗生下降</span>');
Name['Option'][184] = new Array(184,'RateMPDam','RateMPDam','<span title="MPダメージ発生確率" class="help">MPダメ率</span>','<span title="MP damage rate" class="help">MPDamRate</span>','<span title="MP損害發生率" class="help">MP損害率</span>');
Name['Option'][185] = new Array(185,'LPAbsorp','LPAbsorp','LP吸収量','<span title="Absorption LP" class="help">Absor LP</span>','HP吸收量');
Name['Option'][186] = new Array(186,'RateLPAbsorp','RateLPAbsorp','LP吸収確率','<span title="LP absorption probability" class="help">Ab LP rate</span>','HP吸收概率');
Name['Option'][187] = new Array(187,'ValBleeding','ValBleeding','出血効果量','<span title="Bleeding value" class="help">Bleed val</span>','<span title="出血傷害值" class="help">出血/值</span>');
Name['Option'][188] = new Array(188,'RESFireDAM','RESFireDAM','<span title="被火炎属性ダメージ" class="help">被火ダメ</span>','<span title="Fire damage resist" class="help">Fire DAM R</span>','擊中火傷害');
Name['Option'][189] = new Array(189,'RESIceDAM','RESIceDAM','<span title="被冷気属性ダメージ" class="help">被冷ダメ</span>','<span title="Ice damage resist" class="help">Ice DAM R</span>','擊中冰傷害');
Name['Option'][190] = new Array(190,'RESLightningDAM','RESLightningDAM','<span title="被電撃属性ダメージ" class="help">被電属性ダメ</span>','<span title="Lightning damage resist" class="help">Thund DAM R</span>','擊中雷傷害');
Name['Option'][191] = new Array(191,'RESPoisonDAM','RESPoisonDAM','<span title="被毒属性ダメージ" class="help">被毒ダメ</span>','<span title="Poison damage resist" class="help">Poiso DAM R</span>','擊中毒傷害');
Name['Option'][192] = new Array(192,'RESLightDAM','RESLightDAM','<span title="被光属性ダメージ" class="help">被光ダメ</span>','<span title="Light damage resist" class="help">Light DAM R</span>','擊中光傷害');
Name['Option'][193] = new Array(193,'RESDarknessDAM','RESDarknessDAM','<span title="被闇属性ダメージ" class="help">被闇ダメ</span>','<span title="Darkness damage resist" class="help">Dark DAM R</span>','擊中黑暗傷害');
Name['Option'][194] = new Array(194,'GPhyDAM','GPhyDAM','<span title="与物理ダメージ" class="help">与物理ダメ</span>','<span title="Given the physical damage" class="help">G Phy DAM</span>','對物理傷害');
Name['Option'][195] = new Array(195,'GMagDAM','GMagDAM','<span title="与魔法ダメージ" class="help">与魔法ダメ</span>','<span title="Given the magical damage" class="help">G Mag DAM</span>','對魔法傷害');
