Skill = new Array();
for (i=0;i<=2;i++) {
  Skill[i] = new Array();
  for (j=0;j<=24;j++)
    Skill[i][j] = new Array();
}

Skill[0][0][0] = new Array('プロボーク','ウォーリア Lv5','無','挑発をし、わざと怒りを買う。',1,10,0,15,1,'J=0=5','');
Skill[0][0][1] = new Array('回復量増加','ウォーリア Lv12','無','パッシブスキル。ポーション使用時の回復量を増加させる。',0,0,0,0,0,'J=0=12','');
Skill[0][0][2] = new Array('ランジ','ウォーリア Lv18','近接武器','自身の攻撃速度を上昇させる。',1,25,0,30,120,'J=0=18','');
Skill[0][0][3] = new Array('ハイパワー','グラディエイター Lv20','無','パッシブスキル。武器による近接戦のダメージを上昇させる。',0,0,0,0,0,'J=1=20','');
Skill[0][0][4] = new Array('レッグカッティング','グラディエイター Lv20','近接武器','相手の足を狙って攻撃し、動きを鈍らせる。',1,21,0,10,5,'J=1=20','');
Skill[0][0][5] = new Array('フェイス','ナイト Lv20','無','パッシブスキル。外敵からの攻撃を防ぎ被害を減少させる。',0,0,0,0,0,'J=4=20','');
Skill[0][0][6] = new Array('ノーティーマーク','ナイト Lv20','無','挑発をし、わざと怒りを買い、しばらくの間自分に注意を引きつける。',1,12,0,10,10,'J=4=20','');
Skill[0][0][7] = new Array('ウォークライ','グラディエイター Lv28','無','身体能力を上げ、攻撃力を増強させる。',1,31,0.5,1.5,480,'J=1=28','');
Skill[0][0][8] = new Array('プロヴィデンス','ナイト Lv28','無','信仰心を高めることで魔法への抵抗を増加させる。',1,62,0.5,1.5,480,'J=4=28','');
Skill[0][0][9] = new Array('レイジングソウル','グラディエイター Lv35','無','防御を犠牲に、攻撃に集中する。',1,35,0,60,30,'J=1=35','');
Skill[0][0][10] = new Array('ディフェンダー','ナイト Lv35','盾','シールド装備時のみ使用可能。攻撃を犠牲に防御に集中する。',1,35,0,60,30,'J=4=35','');
Skill[0][0][11] = new Array('デスペラード','ジャガーノート Lv45','近接武器','効果中、攻撃力が増加するが、受けるダメージも増加する。一度攻撃すると効果が切れる。',1,39,0,35,60,'J=2=45','');
Skill[0][0][12] = new Array('アニメイトバースト','ジャガーノート Lv50','近接武器','LPが30%減少にする代わりにディレイタイムを半分にする。',1,3,0,0,0,'J=2=50','');
Skill[0][0][13] = new Array('バインディングキャッチ','モンク Lv50','無','背後から命中した時、お互いの動きを止める。',1,47,0,30,10,'J=19=50','');
Skill[0][0][14] = new Array('スラッシュ','近接 3','近接武器','コンボスキルの一つ。素早い一撃を繰り出し、敵に回避する暇を与えない。',1,10,0,10,0,'S=0=3','');
Skill[0][0][15] = new Array('バッシュ','近接 35','斧、両手(剣、槍、鈍器)','相手を強打し、ノックバックと共に気絶効果を与える。',1,18,0,10,0,'S=0=35','');
Skill[0][0][16] = new Array('ミスディレクション','近接 70','無','周りの注意をそらし、自分へのターゲットを解除させる。',1,10,0,60,0,'S=0=70','');
Skill[0][0][17] = new Array('アンペイン','近接 100','無','効果時間中、転倒、移動速度減少、移動不可効果を受けないが、攻撃力が半分になる。',1,24,0,30,10,'S=0=100','');
Skill[0][1][0] = new Array('スライス','斬る 8','片手(剣、斧、槍、鈍器、杖)、短剣','コンボスキルの一つ。素早く二回斬りつける。',1,15,0,10,0,'S=1=8','');
Skill[0][1][1] = new Array('ハッシュ','斬る 71','片手(剣、斧、槍、鈍器)、両手剣、短剣','コンボスキルの一つ。斬る71でスライスが変化。素早く三回斬りつける。相手を出血状態にすることがある。',1,15,0,10,0,'S=1=71','');
Skill[0][1][2] = new Array('回転斬り','斬る 12','両手剣','両手剣のみ使用可能。遠心力を利用し、周囲の敵を一度に攻撃する。',1,28,0,15,0,'S=1=12','');
Skill[0][1][3] = new Array('パリィ','斬る 21','両手(剣、斧、槍、鈍器)、格闘','対象の攻撃を受け流し大きな隙を与える。',1,9,0,10,2,'S=1=21','');
Skill[0][1][4] = new Array('コンセントレーション','斬る 26','無','集中力を高めることで、次の攻撃のみ命中力を上昇させる。',1,18,0,20,120,'S=1=26','');
Skill[0][1][5] = new Array('シュート','斬る 41','近接武器','コンボスキルの一つ。強烈な打ち込みで、相手の防具に関係なく攻撃を叩きつける。',1,14,0,10,0,'S=1=41','');
Skill[0][1][6] = new Array('ソードマスタリー','斬る 61','剣、短剣','パッシブスキル。剣を使用した時のスキル威力が増加する。',0,0,0,0,0,'S=1=61','');
Skill[0][2][0] = new Array('キーンアサルト','ドラグーン Lv45','槍','モーメントを消費し、強力な突き攻撃を行なう。騎乗中のみ使用可能。',1,19,0,9,0,'J=3=45','');
Skill[0][2][1] = new Array('エクスチャージ','ドラグーン Lv50','槍','モーメントを消費し、前方に向かって突進する。騎乗中のみ使用可能。',1,41,0,20,0,'J=3=50','');
Skill[0][2][2] = new Array('エイミング','突く 8','槍','槍を力強く突き出し、前方の敵全てにダメージを与える。',1,16,2,10,0,'S=2=8','');
Skill[0][2][3] = new Array('トリプルスタッブ','突く 26','槍','高速な三回突きを繰り出す。',1,22,0,30,0,'S=2=26','');
Skill[0][2][4] = new Array('ウェポンスタッブ','突く 35','無','効果中、自分の物理攻撃命中時一定確率で落馬効果を与える。',1,28,0,90,60,'S=2=35','');
Skill[0][2][5] = new Array('シューティングスピア','突く 41','槍','力いっぱいに槍を投げつけ、遠くの敵を攻撃する。',1,24,1,30,0,'S=2=41','');
Skill[0][2][6] = new Array('クァッドスタッブ','突く 54','槍','高速な四回突きを繰り出す。トリプルスタッブの硬直中に使用した場合威力が増加する。',1,43,0,16,0,'S=2=54','');
Skill[0][2][7] = new Array('リトート','突く 71','槍','相手が騎乗しているとき、ダメージが増加し、一定確率で落馬させる。',1,13,0,7,0,'S=2=71','');
Skill[0][3][0] = new Array('兜割り','払う 8','斧','クリティカルを狙った勢いのある一撃を行う。',1,19,0,25,0,'S=3=8','');
Skill[0][3][1] = new Array('パリィカウンター','払う 12','両手(剣、斧、槍、鈍器)、格闘','相手の攻撃を受け流し、反撃する。',1,12,0.5,10,2,'S=3=12','');
Skill[0][3][2] = new Array('イエール','払う 21','斧','神経を研ぎ澄まし、行う攻撃がクリティカル攻撃になる確率を上昇させる。',1,30,0,120,60,'S=3=21','');
Skill[0][3][3] = new Array('スプリット','払う 41','斧','地面を斧で切り裂き、自分の前方へ攻撃をしかける。',1,22,0,20,0,'S=3=41','');
Skill[0][3][4] = new Array('フェイタルクラッシュ','払う 71','斧、鈍器、杖、両手剣','コンボスキルの一つ。強力な一撃を与え、気絶状態にする。攻撃に失敗またはブロックされた時は反動を受ける。',1,36,0,15,0,'S=3=71','');
Skill[0][4][0] = new Array('スタンブロウ','打撃 8','杖、鈍器','強力な打撃。相手を一定確率でスタンさせる。',1,15,0,8,0,'S=4=8','');
Skill[0][4][1] = new Array('グランドショック','打撃 26','杖、斧、鈍器','地面を強打し、衝撃で前面周囲にダメージを与える。',1,38,0,18,0,'S=4=26','');
Skill[0][4][2] = new Array('スタンハンマー','打撃 41、祓魔 21','鈍器','地面を強打して強力な地面の振動により周囲の敵を気絶させる。',1,30,0,15,0,'S=4=41_S=15=21','');
Skill[0][4][3] = new Array('アーマーハードヒット','打撃 50','杖、鈍器','力をこめた一撃を防具に行い、装備をはずしてしまう。',1,30,0,15,0,'S=4=50','');
Skill[0][4][4] = new Array('シールドブレイク','打撃 61','斧、鈍器、杖','相手がブロッキング状態だった場合、盾装備不可効果とクリティカルダメージを与える。',1,22,0,10,0,'S=4=61','');
Skill[0][4][5] = new Array('カラップストライク','打撃 71','鈍器、素手','敵に気を送り込み内部から破壊する。対象の防御力が高いほどダメージが増加する。',1,69,0.5,25,0,'S=4=71','');
Skill[0][5][0] = new Array('グレートウォール','ジェネラル Lv45','盾','パッシブスキル。チャージ攻撃を受けた時にブロッキング状態だった場合、ダメージを跳ね返す。',0,0,0,0,0,'J=5=45','');
Skill[0][5][1] = new Array('フィラクテリー','パラディン Lv45','盾','パッシブスキル。ブロッキング状態の時、魔法ダメージもブロックすることができる。',0,0,0,0,0,'J=6=45','');
Skill[0][5][2] = new Array('ディフェンシブアタック','パラディン Lv50','盾','パッシブスキル。ディフェンシブマーチ中の行動制限が解除される。',0,0,0,0,0,'J=6=50','');
Skill[0][5][3] = new Array('ブロッキング','防御 8','盾','盾装着時のみ使用可能。盾を構えて物理攻撃を受けきる。',1,5,0,2,0,'S=5=8','');
Skill[0][5][4] = new Array('シールドバッシュ','防御 12','盾','ブロッキング中のみ使用可能。盾で防御すると同時にそのまま押し返して相手を強打する。',1,14,0,10,2,'S=5=12','');
Skill[0][5][5] = new Array('パラペット','防御 21','無','回避は下がってしまうが、急所を避けクリティカル攻撃を受けにくくする。',1,25,2,30,120,'S=5=21','');
Skill[0][5][6] = new Array('オートガード','防御 26','盾','常に盾が攻撃を受けるようにし、行動中でも自動的に攻撃を防御する。',1,20,0,30,120,'S=5=26','');
Skill[0][5][7] = new Array('シールドタックル','防御 31','盾','ブロッキング中のみ使用可能。盾を構え前面に突進を行い、前方の敵を一定確率で転倒させる。',1,18,0,10,0,'S=5=31','');
Skill[0][5][8] = new Array('ディフェンシブマーチ','防御 41','盾','盾を構えたまま行進を行う事ができる。',1,10,0,5,0,'S=5=41','');
Skill[0][5][9] = new Array('リライアンス','防御 54','無','対象が受けたダメージを全て自分が受ける。',1,16,4,10,300,'S=5=54','');
Skill[0][5][10] = new Array('リラブランシュ','ジェネラル Lv50、防御 54','無','ジェネラルLv50でリライアンスが変化。対象のパーティメンバーが受けるダメージを変わりに受ける。同時に3人まで使用可能。',1,16,4,1,300,'J=5=50_S=5=54','');
Skill[0][5][11] = new Array('エターナルアンセム','防御 61','無','範囲内にいるプレイヤーはスキルを使用することができなくなる。',1,74,0,20,0,'S=5=61','');
Skill[0][6][0] = new Array('鷹の目','アーチャー Lv20','無','パッシブスキル。鷹のような鋭い目配りで、命中力を上昇させる。',0,0,0,0,0,'J=8=20','');
Skill[0][6][1] = new Array('クイックステップ','エージェント Lv20','無','パッシブスキル。素早い動きを心がけ、回避を上昇させる。',0,0,0,0,0,'J=11=20','');
Skill[0][6][2] = new Array('ムーブアシスト','アーチャー Lv28','無','風の祝福をにより追い風を受け、移動速度を増加させる。',1,16,0.5,1.5,480,'J=8=28','');
Skill[0][6][3] = new Array('マインドサイト','エージェント Lv28','無','パーティメンバー全員の命中を増加させる。',1,48,0.5,1.5,480,'J=11=28','');
Skill[0][6][4] = new Array('ステルスワーク','ディスターバンス Lv45','無','パッシブスキル。クローキング時に罠を置いてもハイディング状態が解除されなくなる。',0,0,0,0,0,'J=13=45','');
Skill[0][7][0] = new Array('ラピッドスタンス','アーチャー Lv35','クロスボウ','素早い動きでクロスボウを連射できるようにする。',1,45,0,45,0,'J=8=35','');
Skill[0][7][1] = new Array('スナイプモード','スナイパー Lv45','弓、クロスボウ','攻撃力・命中・射程距離が増加し移動不可となる。もう一度使用すると効果が切れる。',1,45,2,5,0,'J=9=45','');
Skill[0][7][2] = new Array('キンドルアロー','スナイパー Lv50','弓','指定した地点を火の弓で燃やし、炎のフィールドを作り出す。',1,41,1,15,0,'J=9=50','');
Skill[0][7][3] = new Array('トレースアイ','プレデター Lv45','無','視界内にいるハイディング状態の敵を目視でき、ダメージが増加するが移動不可となる。',1,44,2,20,0,'J=10=45','');
Skill[0][7][4] = new Array('アローフューゼレイド','プレデター Lv50','クロスボウ','パッシブスキル。クロスボウ使用時に射程距離が増加し、2連射になる。',0,0,0,90,0,'J=10=50','');
Skill[0][7][5] = new Array('フレーミングアロー','射撃 8','弓、クロスボウ','炎の矢を放つ。',1,12,0,30,0,'S=7=8','');
Skill[0][7][6] = new Array('ポイズンショット','射撃 12','弓、クロスボウ','毒の矢を放ち、相手を毒状態にする。',1,12,0,30,0,'S=7=12','');
Skill[0][7][7] = new Array('アングルショット','射撃 26','弓','対象地点へ矢の雨を降らせるように、上空目掛けて高角で矢を放つ。',1,15,1,5,0,'S=7=26','');
Skill[0][7][8] = new Array('アローストーム','射撃 61','弓','射撃61でアングルショットが変化。対象地点へ矢の嵐を降らせ、連続でダメージを与える。',1,15,1,5,0,'S=7=61','');
Skill[0][7][9] = new Array('マルチショット','射撃 41、仕掛 21','クロスボウ','矢を同時に5方向に発射する事ができる。',1,20,0,30,0,'S=7=41_S=10=21','');
Skill[0][7][10] = new Array('チャージショット','射撃 50、暗殺 21','弓','対象をノックバックさせる強力な矢を放つ。',1,18,0,30,0,'S=7=50_S=9=21','');
Skill[0][7][11] = new Array('シャットキャスティング','射撃 54','弓、クロスボウ','命中した相手を沈黙状態にする、一定確率で長い沈黙を相手に与える。',1,33,0,10,0,'S=7=54','');
Skill[0][7][12] = new Array('シャドースナッチ','射撃 71','弓、クロスボウ','相手の背後に命中した場合、移動不可効果を与える。攻撃が命中すると効果が解除される。',1,49,0,30,0,'S=7=71','');
Skill[0][8][0] = new Array('クリエイトポイズン','調合 8','猛毒草*1、空の容器*1','猛毒草、空の容器を消費し、毒薬を作成する事ができる。',1,3,1,0,0,'S=8=8','');
Skill[0][8][1] = new Array('フォックスグローブ','調合 12','毒薬*1','毒薬を費やし、自分の武器に薬を塗る。一定時間、攻撃に毒発生効果が付与される。',1,15,2,10,120,'S=8=12','');
Skill[0][8][2] = new Array('シーラム','調合 26','解毒草*1、空の容器*1','解毒草、空の容器を消費し、解毒薬を作成する。',1,3,1,0,0,'S=8=26','');
Skill[0][8][3] = new Array('ベーシックフュージョン','調合 41','月光草*1、蓬莱花*1、空の容器*1','月光草、蓬莱花、空の容器を消費し、神秘のポーションを作成する。',1,3,0,0,0,'S=8=41','');
Skill[0][8][4] = new Array('エピデミックコラプト','調合 50','毒薬*1','攻撃命中時に対象が詠唱中だった場合、詠唱速度減少を与える。毒薬を1つ消費する。',1,31,0,0,150,'S=8=50','');
Skill[0][8][5] = new Array('ビルトキシン','調合 61','無','パッシブスキル。フォックスグローブ使用時のオーラダメージが増加する。',0,0,0,0,0,'S=8=61','');
Skill[0][8][6] = new Array('クリアヴィジョン','調合 71','無','効果中、命中が増加し、敵が設置した罠が見えるようになる。',1,44,0.5,20,10,'S=8=71','');
Skill[0][9][0] = new Array('ハイディング','スカウト Lv18','無','その場で姿を隠すことができる。',1,24,0,3,0,'J=7=18','');
Skill[0][9][1] = new Array('クローキング','エージェント Lv20','無','ハイディング状態になり、そのまま移動することができる。',1,45,2,30,0,'J=11=20','');
Skill[0][9][2] = new Array('オスモシスボディ','アサシン Lv45','無','パッシブスキル。クローキング時の移動ペナルティが無くなり、マナが少し自動で回復する。',0,0,0,0,0,'J=12=45','');
Skill[0][9][3] = new Array('ヴェラッシングチャンス','アサシン Lv50','格闘','パッシブスキル。格闘武器使用時、低威力で追加攻撃が発動する。',0,0,0,90,0,'J=12=50','');
Skill[0][9][4] = new Array('バックスタブ','暗殺 8','短剣、格闘','暗器装備時のみ使用可能。相手の背後から攻撃をした場合、強力な一撃を与える突き攻撃。',1,15,0,30,0,'S=9=8','');
Skill[0][9][5] = new Array('ダガースロー','暗殺 12','短剣','暗器装備時のみ使用可能。素早く近くの敵に短剣を投げつける。',1,10,0,5,0,'S=9=12','');
Skill[0][9][6] = new Array('ラッシュ','暗殺 26','短剣、格闘','防御をかえりみない代わりに、素早い速度で対象を攻撃できるようになる。(習得条件/暗殺、所属/斬る)',1,30,0,90,0,'S=9=26','');
Skill[0][9][7] = new Array('サプライズアタック','暗殺 41','短剣、格闘','ハイディング状態時使用可能。攻撃命中時ハイディング状態が解除されない。',1,15,0,5,0,'S=9=41','');
Skill[0][9][8] = new Array('鎧通し','暗殺 54','短剣、格闘','転倒している相手の鎧の隙間を狙い攻撃する。防御力を無視した大ダメージを与える。',1,15,0,10,0,'S=9=54','');
Skill[0][9][9] = new Array('リシディバイト','暗殺 71','短剣、格闘','相手の背後に命中した場合、このスキル以外のディレイタイムを全て解除する。',1,58,0,55,0,'S=9=71','');
Skill[0][10][0] = new Array('リムーブトラップ','仕掛 8','無','指定した地点から一定範囲に設置された罠を、敵味方の区別無く解除する。',1,10,1,10,0,'S=10=8','');
Skill[0][10][1] = new Array('グルーキャッチ','仕掛 16','罠*1','相手の足を捕らえ、移動不可状態にする罠を設置する。罠を１つ消費する。',1,20,1.5,3,0,'S=10=16','');
Skill[0][10][2] = new Array('エクスマイン','仕掛 26','罠*1','踏むと爆発し、周囲にダメージを与える罠を設置する。罠を1つ消費する。',1,30,1.5,3,0,'S=10=26','');
Skill[0][10][3] = new Array('ワームボム','仕掛 41','罠*2','前方に向かって直進し、触れると爆発する罠を設置する。罠を2つ消費する。',1,33,3,5,0,'S=10=41','');
Skill[0][10][4] = new Array('カームスポット','仕掛 50','無','効果範囲内にいるプレイヤーは、フィールドに作用するスキル効果を無効にする。',1,46,1.5,8,0,'S=10=50','');
Skill[0][10][5] = new Array('インピッドモノリス','仕掛 61','罠*1','馬のみに効果発動。踏んだプレイヤーの周囲の4方向に壁を出現させ、閉じ込める。',1,48,1.5,3,0,'S=10=61','');
Skill[0][10][6] = new Array('メルトマインド','仕掛 71','罠*1','相手のMPを減少させる罠を設定する。罠を1つ消費する。',1,48,1.5,3,0,'S=10=71','');
Skill[0][11][0] = new Array('アナバシス','スカウト Lv12','無','自身の移動速度を上昇させる。',1,16,0,10,180,'J=7=12','');
Skill[0][11][1] = new Array('バックステップ','技巧 3','無','素早く後ろにあとずさる。(回避+100)',1,5,0,3,1,'S=6=3','');
Skill[0][11][2] = new Array('ダッシュ','回避 8','無','瞬間的に脚力を上げ、高速に移動する事が出来る。(2秒)',1,18,0,30,2,'S=11=8','');
Skill[0][11][3] = new Array('ファストアボイド','回避 16','無','自身の回避力を増加させる。',1,35,0,90,60,'S=11=16','');
Skill[0][11][4] = new Array('タングルハンド','回避 21','無','相手の命中力を減少させる。',1,22,0,30,0,'S=11=21','');
Skill[0][11][5] = new Array('ラムセンス','回避 26','無','パッシブスキル。転倒耐性、気絶耐性、凍傷耐性+15％。',0,0,0,0,0,'S=11=26','');
Skill[0][11][6] = new Array('アボイダンス','回避 41','無','効果時間中、回避を増加させる。2回物理攻撃をされると効果が終了する。',1,38,0.5,30,0,'S=11=41','');
Skill[0][11][7] = new Array('インスレイトセンス','回避 50','無','パッシブスキル。一定確率で敵からの魔法を回避することができる。',0,0,0,0,0,'S=11=50','');
Skill[0][11][8] = new Array('フェアウィンド','回避 66','無','対象のプレイヤーにダッシュの効果を与える。',1,29,1,1.5,2,'S=11=66','');
Skill[0][12][0] = new Array('メディテーション','アコライト Lv12','無','パッシブスキル。座った状態での深い精神統一により、マナの回復量を上昇させる。',0,0,0,0,0,'J=14=12','');
Skill[0][12][1] = new Array('インスピレーション','プリースト Lv20','無','パッシブスキル。感覚を研ぎ澄まし、霊感を上昇させる。',0,0,0,0,0,'J=15=20','');
Skill[0][12][2] = new Array('ホーリーディバイン','アセティック Lv20','無','パッシブスキル。光のオーラの装備を身に付けると、魅了・魔術に対する抵抗を得る。',0,0,0,0,0,'J=18=20','');
Skill[0][12][3] = new Array('フィジカルバリア','祈祷 102','無','対象に物理攻撃を1度だけ完全に防ぐバリアを張る。',1,128,2,10,120,'S=12=102','');
Skill[0][12][4] = new Array('マジックバリア','祈祷 102','無','対象に魔法攻撃を1度だけ完全に防ぐバリアを張る。',1,128,2,10,120,'S=12=102','');
Skill[0][13][0] = new Array('ヒール','アコライト Lv8','無','治癒の魔法でライフを回復させる事ができる。',1,62,2,3,0,'J=14=18','');
Skill[0][13][1] = new Array('レイズデッド','プリースト Lv35','無','戦いに倒れてしまった者を復活させる事が出来る。聖水を3つ消費する。',1,65,5,30,0,'J=15=35','');
Skill[0][13][2] = new Array('テンプルム','クレリック Lv45','無','聖域を作り出し、範囲内にいるプレイヤー全員のLPを回復させる。',1,87,5,60,0,'J=16=45','');
Skill[0][13][3] = new Array('マグナウェリタス','クレリック Lv50','無','パッシブスキル。大いなる慈愛の力によりLP回復スキルの力を引き出すことができる。',0,0,0,0,0,'J=16=50','');
Skill[0][13][4] = new Array('ウァリエタース','エンチャンター Lv50','無','パッシブスキル。良い効果の祝福スキルは効果範囲が自分の周囲にいる味方全員になる。',0,0,0,0,0,'J=17=50','');
Skill[0][13][5] = new Array('ファーストエイド','慈愛 8','無','治癒の魔法でライフを回復させることができる。',1,28,1,4,0,'S=13=8','');
Skill[0][13][6] = new Array('ミスリデート','慈愛 12','無','毒にかかってしまった者を解毒することが出来る。',1,15,1,3,0,'S=13=12','');
Skill[0][13][7] = new Array('リクライム','慈愛 21','無','治癒の魔法を宿らせ、一定時間ライフを回復させ続ける。',1,40,1.5,5,120,'S=13=21','');
Skill[0][13][8] = new Array('アウェイクン','慈愛 26','無','睡眠、気絶、凍傷を治療する事ができる。',1,18,1,3,0,'S=13=26','');
Skill[0][13][9] = new Array('リストレーション','慈愛 41','無','パーティメンバー全員のライフを回復させ続ける事が出来る。',1,90,3,20,120,'S=13=41','');
Skill[0][13][10] = new Array('ヒールスウェル','慈愛 54','無','パーティメンバー全員のライフを大きく回復させる事が出来る。',1,256,1,30,0,'S=13=54','');
Skill[0][13][11] = new Array('コンプリートセラピー','慈愛 71','無','対象の状態異常を全て回復させ、状態異常耐性を増加させる。',1,76,1.5,35,15,'S=13=71','');
Skill[0][14][0] = new Array('ギブンリポーズ','プリースト Lv20','無','パーティーメンバー全員のマナの回復速度を上昇させる。',1,50,5,20,120,'J=15=20','');
Skill[0][14][1] = new Array('ディバインエイド','プリースト Lv28','無','生命を祝福する事により、パーティメンバー全員の最大ライフ量を増加させる。',1,89,4,1.5,480,'J=15=28','');
Skill[0][14][2] = new Array('エンハンスエンチャント','エンチャンター Lv45','無','対象の味方プレイヤーにオーラダメージを増加させる効果を与える。',1,68,0.5,1.5,480,'J=17=45','');
Skill[0][14][3] = new Array('グラーティア','祝福 8','無','対象の攻撃速度を増加させる。',1,26,0.5,1.5,480,'S=14=8','');
Skill[0][14][4] = new Array('ラピスメディオ','祝福 12','無','対象の物理防御力を増加させる。',1,22,0.5,1.5,480,'S=14=12','');
Skill[0][14][5] = new Array('インペディメンタ','祝福 21','無','対象の移動速度を減少させる。',1,33,1.5,10,10,'S=14=21','');
Skill[0][14][6] = new Array('ウィンクルム','祝福 26','無','パーティーメンバー全員の受けるダメージを軽減できる。',1,70,1,1.5,120,'S=14=26','');
Skill[0][14][7] = new Array('アクアエリムス','祝福 41','空の容器*1','空の容器を消費し、聖水を作成する。',1,4,1,0,0,'S=14=41','');
Skill[0][14][8] = new Array('サルタティオ','祝福 54','無','一定時間の間、自分以外の対象が使用するスキルの詠唱速度を約30%増加させる。',1,31,0,5,90,'S=14=54','');
Skill[0][14][9] = new Array('プロエリウム','祝福 61','無','対象の筋力、敏捷、知性を増加させる。',1,78,0.5,1.5,480,'S=14=61','');
Skill[0][15][0] = new Array('レックスナチュラリス','アセティック Lv20','無','MPを一定時間、少しづつ回復させることができる。',1,32,1.5,10,120,'J=18=20','');
Skill[0][15][1] = new Array('ウィンドアシスト','アセティック Lv28','無','パーティーメンバー全員の回避を増加させる。',1,55,0,1,480,'J=18=28','');
Skill[0][15][2] = new Array('プロジェニー','モンク Lv45','無','パッシブスキル。害を与える魔法効果の効果時間を減少させる。',0,0,0,0,0,'J=19=45','');
Skill[0][15][3] = new Array('スワップマナ','エクソシスト Lv45','無','対象のプレイヤーと自分のMPを入れ替える。',1,16,2,10,0,'J=20=45','');
Skill[0][15][4] = new Array('スワップソウル','エクソシスト Lv50','無','自分と相手にかかっている魔法効果を全て入れ替える。',1,21,1,10,0,'J=20=50','');
Skill[0][15][5] = new Array('リビティウム','祈祷 35','無','害を与えていた魔法効果を1つ打ち消す。',1,14,2,60,0,'S=12=35','');
Skill[0][15][6] = new Array('チャスタイズ','祓魔 8','無','光で作られた矢を飛ばす。悪魔やアンデットに効果が高い。',1,18,1,5,0,'S=15=8','');
Skill[0][15][7] = new Array('スワロウエレメント','祓魔 12','無','火炎・冷気・電撃魔法のダメージを軽減する。',1,60,0.8,10,60,'S=15=12','');
Skill[0][15][8] = new Array('ホーリーウェポン','祓魔 26','無','武器に聖なる祝福を宿らせる。',1,30,1.5,1.5,480,'S=15=26','');
Skill[0][15][9] = new Array('レメディウム','祓魔 41','無','祝福により、害を与えていた魔法効果を１つ打ち消す。聖水を1つ消費する。',1,26,1,5,0,'S=15=41','');
Skill[0][15][10] = new Array('デシプリンサークル','祓魔 54','無','自分の周囲に光の柱を出現させダメージを与える。',1,132,6,60,0,'S=15=54','');
Skill[0][15][11] = new Array('アンサモン','祓魔 61','無','範囲内にある、召還された物を消滅させる。',1,41,5,10,0,'S=15=61','');
Skill[0][15][12] = new Array('ディヴォーション','祝福 20、祓魔 61','無','対象がスキルを使用する時のMPを、自分が肩代わりする。同時に4人まで使用可能。',1,50,3,0.5,0,'S=14=20_S=15=61','');
Skill[0][15][13] = new Array('クワイエティズム','祓魔 71','無','範囲内のフィールドに作用するスキルを無効にし、地点指定をすることができなくなる。',1,93,5,12,120,'S=15=71','');
Skill[0][16][0] = new Array('詩人の歌','聖歌 8','無','集中力を高める歌を歌う。効果内のプレイヤーの命中・回避増加。',1,30,0,5,0,'S=16=8','');
Skill[0][16][1] = new Array('ルミナスチャント','聖歌 21','無','パッシブスキル。聖歌スキル使用中に、熟練度に応じて移動が可能となる。',0,0,0,0,0,'S=16=21','');
Skill[0][16][2] = new Array('平和の歌','慈愛 61、聖歌 30','無','防御力を増加させる歌を歌う。効果内のプレイヤーは一定以下のダメージを無効にする。',1,33,0,5,0,'S=13=61_S=16=30','');
Skill[0][16][3] = new Array('魔力の歌','祝福 71、聖歌 30','無','魔力を増加させる歌を歌う。効果内のプレイヤーの魔法攻撃力を増加、ディレイタイム減少。',1,33,0,5,0,'S=14=71_S=16=30','');
Skill[0][17][0] = new Array('魔力上昇','ウィザード Lv20','無','パッシブスキル。多彩な魔法の知識を得て、魔法威力を上昇させる。',0,0,0,0,0,'J=22=20','');
Skill[0][17][1] = new Array('ダークバインド','ダークロア Lv20','無','パッシブスキル。闇のオーラ装備を身につけると、火炎・冷気・電撃・毒に対する抵抗を得る。',0,0,0,0,0,'J=25=20','');
Skill[0][18][0] = new Array('ファイアボルト','メイジ Lv1','無','火炎でつくられた矢を飛ばしダメージを与える。',1,28,0.8,2,0,'J=21=1','');
Skill[0][18][1] = new Array('フラッシュ','メイジ Lv12','無','電撃で作られた矢を遠くに飛ばす。',1,44,0.5,20,0,'J=21=12','');
Skill[0][18][2] = new Array('サンダークラッシュ','ウィザード Lv20','無','電撃の矢を遠くに飛ばす。',1,78,3.5,12,0,'J=22=20','');
Skill[0][18][3] = new Array('セントラライズ','ウォーロック Lv45','無','自分が次に使用する魔法威力を増加させる。',1,56,2.5,15,0,'J=23=45','');
Skill[0][18][4] = new Array('ヘイルストーン','元素 8','無','素早く氷の塊を作り、対象に飛ばす。',1,18,0.3,2,4,'S=18=8','');
Skill[0][18][5] = new Array('サンダーボール','元素 12','無','対象に電撃の塊を飛ばし周囲に電撃ダメージを与える。',1,50,2,5,0,'S=18=12','');
Skill[0][18][6] = new Array('アイススピア','元素 21','無','素早く鋭い氷の矢を作り出し、対象に飛ばす。',1,59,1.5,5,0,'S=18=21','');
Skill[0][18][7] = new Array('ファイアストーム','元素 26','無','自分の周囲に火炎の竜巻を発生させる。',1,100,6,30,0,'S=18=26','');
Skill[0][18][8] = new Array('レジストファイア','元素 33','無','対象の火炎耐性を増加させるが、冷気耐性、電撃耐性を減少させる。',1,32,1.5,3.5,0,'S=18=33','');
Skill[0][18][9] = new Array('レジストアイス','元素 33','無','対象の冷気耐性を増加させるが、火炎耐性、電撃耐性を減少させる。',1,32,1.5,3.5,0,'S=18=33','');
Skill[0][18][10] = new Array('レジストサンダー','元素 33','無','対象の電撃耐性を増加させるが、火炎耐性、冷気耐性を減少させる。',1,32,1.5,3.5,0,'S=18=33','');
Skill[0][18][11] = new Array('アイスゾーン','元素 54','無','素早く一帯に冷気の渦を作り上げる。',1,112,7.5,20,0,'S=18=54','');
Skill[0][18][12] = new Array('アイステンペスト','元素 71','無','元素71でアイスゾーンが変化。広範囲に強力な冷気の渦を作り上げ、命中した相手を確実にノックバックさせる。',1,287,7.5,20,0,'S=18=71','');
Skill[0][18][13] = new Array('ディレイドボム','元素 61','無','対象を一定時間後に爆破する。威力は爆破までに掛かった時間に依存する。',1,61,2,6,0,'S=18=61','');
Skill[0][18][14] = new Array('サンダーストーム','祓魔 40、元素 61','無','指定した地点に雷を発生させる。騎乗していると移動することができなくなる。',1,227,20,20,0,'S=15=40_S=18=61','');
Skill[0][18][15] = new Array('メテオストーム','元素 61、具現 40','無','指定した地点の周囲に隕石を落下させる。気絶効果を与えることがある。',1,312,20,20,0,'S=18=61_S=19=40','');
Skill[0][19][0] = new Array('メモライズ','コンジュラー Lv45','無','ワープ先を1つまで記憶する。一部マップのみ使用可能となりマップ移動で効果が切れる。',1,10,1,5,0,'J=24=45','');
Skill[0][19][1] = new Array('トランスポート','コンジュラー Lv45','無','メモライズで記憶した場所と現在の場所を繋ぐワープを出現させる。',1,24,2,300,0,'J=24=45','');
Skill[0][19][2] = new Array('インテレット','コンジュラー Lv50','無','パッシブスキル。メモライズで記憶できる場所を1つ増加させることができる。',0,0,0,0,0,'J=24=50','');
Skill[0][19][3] = new Array('マインドスプリーム','コンジュラー Lv50','無','パッシブスキル。精神の鍛錬により、具現スキルを強化することができる。',0,0,0,0,0,'J=24=50','');
Skill[0][19][4] = new Array('ソウルブライト','具現 8','無','自分の周囲を照らし、ハイディング状態を解除させる。',1,14,1,7,0,'S=19=8','');
Skill[0][19][5] = new Array('マナシールド','具現 21','無','攻撃を受ける度にマナを消費するが、自分が受ける物理ダメージを軽減させる。',1,24,3,10,0,'S=19=21','');
Skill[0][19][6] = new Array('フォローウィンド','具現 31','無','風を身に纏うことで、詠唱を妨害されにくくなる。',1,59,5,1.5,0,'S=19=31','');
Skill[0][19][7] = new Array('フライングエッジ','具現 41','無','念で作られた刃を対象に飛ばす。ダメージは相手の防御力に依存する。',1,39,3.5,10,0,'S=19=41','');
Skill[0][19][8] = new Array('ペインシェントウォール','具現 50','無','巨大な壁を具現化する。全てのプレイヤーは通過することができない。',1,79,5,120,150,'S=19=50','');
Skill[0][19][9] = new Array('コールサンドマン','具現 61','無','巨大な竜巻を召還しダメージを与える。相手を眠らせることがある。',1,58,7,15,0,'S=19=61','');
Skill[0][19][10] = new Array('イーヴルプラント','具現 71','無','指定した地点に植物を召還する。植物は近くの敵に対して遠距離攻撃を行う。攻撃命中時、一定確率で毒の効果を付与する。',1,64,2,10,0,'S=19=71','');
Skill[0][20][0] = new Array('ダークフィッテスト','カラミティ Lv45','無','パッシブスキル。闇のオーラによる反動ダメージを軽減する。',0,0,0,0,0,'J=27=45','');
Skill[0][20][1] = new Array('ステルストリップ','カラミティ Lv50','無','範囲内のパーティメンバーをハイディング状態にする。',1,240,3,120,300,'J=27=50','');
Skill[0][20][2] = new Array('ポイズンシェル','暗黒 8','無','対象の体内に毒を送り込み、毒状態にする。',1,12,2,5,0,'S=20=8','');
Skill[0][20][3] = new Array('グルーミーエフェクト','暗黒 16','無','武器に暗黒の力を宿らせる。',1,38,2,10,120,'S=20=16','');
Skill[0][20][4] = new Array('ブラッドドレイン','暗黒 21','無','相手の生命力を抜き出し、自分のものとしてしまう。',1,32,1,10,0,'S=20=21','');
Skill[0][20][5] = new Array('ベノムコロージョン','暗黒 26','無','小さな傷口から相手の体内に毒を送り込み、腐食状態にする。',1,33,2.5,10,0,'S=20=26','');
Skill[0][20][6] = new Array('ディスペル','暗黒 33','無','対象の強化魔法効果を１つ打ち消す。',1,26,1,15,0,'S=20=33','');
Skill[0][20][7] = new Array('レジストマリス','暗黒 35','無','対象の毒耐性、闇耐性を増加させるが、魅了耐性を減少させる。',1,32,1.5,3.5,20,'S=20=35','');
Skill[0][20][8] = new Array('エーテルフレア','暗黒 41','無','次に受けるダメージを倍増させる罰を与える。',1,23,0.5,10,0,'S=20=41','');
Skill[0][20][9] = new Array('ヘイトリッドペスト','暗黒 54','無','地面から負のオーラを呼出し、毒属性のダメージを与える。稀に相手を衰弱状態にする。',1,62,5,6,0,'S=20=54','');
Skill[0][20][10] = new Array('ストリップフォース','暗黒 61','無','パッシブスキル。効果中、物理攻撃を行なうと、一定確率で対象の強化魔法を打ち消す。',0,0,0,0,0,'S=20=61','');
Skill[0][20][11] = new Array('ダークフレンジー','暗黒 71','無','武器に強力な闇のオーラを付与し、周囲にダメージを与える。',1,122,3,10,6,'S=20=71','');
Skill[0][21][0] = new Array('タイムステイシス','ジェスター Lv45','無','このスキルの効果中、害を与える魔法効果の効果時間を停止させる。',1,31,2,15,0,'J=26=45','');
Skill[0][21][1] = new Array('ホリッドミラージュ','ジェスター Lv50','無','幻覚を見せることで騎手を混乱させ、馬の脚力を減少させる。',1,58,1,10,60,'J=26=50','');
Skill[0][21][2] = new Array('フィーブル','惑乱 8','無','対象の攻撃力を減少させる。',1,18,1,5,120,'S=21=8','');
Skill[0][21][3] = new Array('サンドマントルネード','惑乱 12','無','足元から砂の竜巻をおこし物理ダメージと同時に睡眠効果を与える。',1,51,2,20,20,'S=21=12','');
Skill[0][21][4] = new Array('サイオニックブラスト','惑乱 21','無','マナを使った精神による攻撃で、相手の精神に直接ダメージを与える。',1,25,1.5,5,0,'S=21=21','');
Skill[0][21][5] = new Array('ウィークネス','惑乱 26','無','対象の防御力を減少させる。',1,18,1,5,120,'S=21=26','');
Skill[0][21][6] = new Array('スロウイベイド','惑乱 33','無','対象の回避を減少させる。',1,28,2,5,120,'S=21=33','');
Skill[0][21][7] = new Array('レジストチャーム','惑乱 35','無','対象の魅了耐性を増加させるが、毒耐性、闇耐性を減少させる。',1,32,1.5,3.5,7,'S=21=35','');
Skill[0][21][8] = new Array('チルストライク','惑乱 41','無','素早く対象に冷気ダメージを与え、凍傷状態にする。',1,44,0.3,12,15,'S=21=41','');
Skill[0][21][9] = new Array('ベノムスワンプ','惑乱 54','無','沼地を作り出し、素早さを封じて移動を困難にさせてしまう。',1,44,0.5,30,30,'S=21=54','');
Skill[0][21][10] = new Array('サイレンストーム','惑乱 61','無','範囲内にいる敵のマナにダメージを与える。相手を沈黙にすることがある。',1,99,4.5,15,0,'S=21=61','');
Skill[0][21][11] = new Array('プレイグカース','惑乱 71','無','対象にボルトを放つ。命中した敵とその周囲の敵に一定確率で呪いと病気の効果を与える。',1,69,2,20,30,'S=21=71','');
Skill[0][24][0] = new Array('メレーライディング','ドラグーン Lv45','無','パッシブスキル。騎乗時に一部スキルとチャージ攻撃を使用することができる。',0,0,0,0,0,'J=3=45','');
Skill[0][24][1] = new Array('メレーライディング','パラディン Lv45','無','パッシブスキル。騎乗時に一部スキルとチャージ攻撃を使用することができる。',0,0,0,0,0,'J=6=45','');
Skill[0][24][2] = new Array('ヤブサメライディング','プレデター Lv45','無','パッシブスキル。騎乗時に一部スキルとチャージ攻撃を使用することができる。',0,0,0,0,0,'J=10=45','');
Skill[0][24][3] = new Array('メディアライディング','カラミティ Lv45','無','パッシブスキル。騎乗時に一部スキルとチャージ攻撃を使用することができる。',0,0,0,0,0,'J=27=45','');
Skill[0][24][4] = new Array('サモンヴィークル','騎乗 20','無','騎乗可能な場所であれば、馬を呼び出すことができる。',1,22,3,180,0,'S=24=20','');
Skill[0][24][5] = new Array('ホースプロテクション','騎乗 31','盾','効果中、馬が受けるはずのダメージを自分が受ける。',1,5,0,0,0,'S=24=31','');
Skill[1][0][0] = new Array('Provoke','Warrior Lv5','None','Taunts monsters to come toward you. Used in tanking or pulling mobs in from their pack (soloing).');
Skill[1][0][1] = new Array('Recovery Effects increased','Warrior Lv12','None','Increases the effectiveness of potions.');
Skill[1][0][2] = new Array('Lunge','Warrior Lv18','Melee Weapon','Increases the caster&#39;s Attack Speed. Can only be cast to self.');
Skill[1][0][3] = new Array('Empower','Gradiator Lv20','None','Boosts melee weapon&#39;s attacking power. Passive skill.');
Skill[1][0][4] = new Array('Leg Sweep','Gradiator Lv20','Melee Weapon','Attack aimed at the feet to slow down movement speed.');
Skill[1][0][5] = new Array('Guard','Knight Lv20','None','Reduces the damage of incoming attacks through guarding in a defense stance.');
Skill[1][0][6] = new Array('Obscene Gesture','Knight Lv20','None','Taunts the enemy in order to enrage them&#44; and draws their attention for a short while.');
Skill[1][0][7] = new Array('War Cry','Gradiator Lv28','None','Increases Physical Attack Power of all party members.');
Skill[1][0][8] = new Array('Providence','Knight Lv28','None','Increases the magical resistance of all party members by increasing their faith.');
Skill[1][0][9] = new Array('Raging Soul','Gradiator Lv35','None','Concentrate to increase Attack Power at the expense of Defense.');
Skill[1][0][10] = new Array('Phalanx','Knight Lv35','Shield','Sacrifices your attack power to focus on defense. Can only be used when a shield is equipped.');
Skill[1][0][11] = new Array('Desperado','Juggernaut Lv45','Melee Weapon','+ Increased Physical attack power to self - Reduced Physical Defense to self.');
Skill[1][0][12] = new Array('Skill Focus','Juggernaut Lv50','Melee Weapon','Your Skill Cooldowns are reduced by half in exchange of 30% of your LP.');
Skill[1][0][13] = new Array('Paralyzing Bond','Monk Lv50','None','When the player is hit from behind&#44; both player and the enemy are rendered Immobile.');
Skill[1][0][14] = new Array('Slash','Melee 3','Melee Weapon','A very quick slash that won&#39;t allow an enemy time to evade. One of the combo skills.');
Skill[1][0][15] = new Array('Bash','Melee 35','Axe&#44; 2H Sword&#44; 2H Spear&#44; 2H Blunt','Knocks back opponents while inflicting Stun status effect.');
Skill[1][0][16] = new Array('Misdirection','Melee 70','None','Distracts the enemy&#44; causing them to lose you as their target&#44;');
Skill[1][0][17] = new Array('Ossify','Melee 100','None','+ Knockdown immunity - Attack power reduced (halved?) - Move speed reduced - Unable to move (Immobile)');
Skill[1][1][0] = new Array('Slice','Slash 8','1H Sword&#44; 1H Axe&#44; 1H Spear&#44; 1H Blunt&#44; 1H Wand&#44; Knife','Swiftly perform 2 slashes at the enemy. One of the combo skills.');
Skill[1][1][1] = new Array('Dice','Slash 71','1H Sword&#44; 2H Sword 1H Axe&#44; 1H Spear&#44; 1H Blunt&#44; Knife','Uses centrifugal force to attack all nearby enemies at once. Used only with 2-handed swords.');
Skill[1][1][2] = new Array('Whirling Strike','Slash 12','2H Sword','Allows a 2-second window to parry an incoming melee attack at your front. Futile against back/side attacks.');
Skill[1][1][3] = new Array('Parry','Slash 21','2H Sword&#44; 2H Axe&#44; 2H Blunt&#44; 2H Spear&#44; Fist','Adds +100 Accuracy only for your next single attack.');
Skill[1][1][4] = new Array('Concentration','Slash 26','None','Intense strike that can pierce through armor.');
Skill[1][1][5] = new Array('Brutal Strike','Slash 41','Melee Weapon','Increases attacking power of Slash Skills while using a sword.');
Skill[1][1][6] = new Array('Sword Mastery','Slash 61','Sword&#44; Knife','3 quick slashes that may inflict Bleeding status to the victim.');
Skill[1][2][0] = new Array('Equine Charge','Dragoon Lv45','Spear','Consumes a Moment to make a powerful thrust/charge. Only available while Riding.');
Skill[1][2][1] = new Array('Charge','Dragoon Lv50','Spear','Uses Moment to lunge toward the front. Only available while Riding.');
Skill[1][2][2] = new Array('Heave','Thrust 8','Spear','Skewer all targets at your front in a straight line. Medium range attack.');
Skill[1][2][3] = new Array('Triple Stab','Thrust 26','Spear','Unleash 3 quick consecutive stabs on a single target. Half-second Rigid after use.');
Skill[1][2][4] = new Array('Dismounting Stab','Thrust 35','None','Allows a chance to dismount an opponent off a horse upon attack hit.');
Skill[1][2][5] = new Array('Spear Volley','Thrust 41','Spear','Throws spear towards distant targets.');
Skill[1][2][6] = new Array('Quadruple Stab','Thrust 54','Spear','Unleash 4 quick consecutive stabs on a single target. Attack power is increased when used while in Rigid State (after using Triple Stab).');
Skill[1][2][7] = new Array('Horse Assault','Thrust 71','Spear','+ Increased damage to mounted targets + Chance to dismount target');
Skill[1][3][0] = new Array('Clobber','Cleave 8','Axe','Performs a furious attack in an attempt to land a critical hit.');
Skill[1][3][1] = new Array('Riposte','Cleave 12','2H Sword&#44; 2H Axe&#44; 2H Spear&#44; 2H Blunt&#44; Fist','2-second window to parry a melee attack at your front then counterattack.');
Skill[1][3][2] = new Array('Roar','Cleave 21','Axe','Sharpens the nerves to increase probability of critical attacks.');
Skill[1][3][3] = new Array('Split','Cleave 41','Axe','A ground-splitting axe attack that strikes the area in front of you.');
Skill[1][3][4] = new Array('Desperate Strike','Cleave 71','Axe&#44; Blunt&#44; Wand&#44; 2H Sword','Strikes your opponent with a mighty attack&#44; Knocking them out. If your attack fails or is blocked the effect is reversed.');
Skill[1][4][0] = new Array('Stun','Bash 8','Blunt&#44; 2H Blunt&#44; Wand','Powerful strike plus a chance to stun the victim.');
Skill[1][4][1] = new Array('Grand Shock','Bash 26','Blunt&#44; 2H Blunt&#44; Axe&#44; 2H Axe&#44; Wand','Strikes the ground hard&#44; damaging your opponent with a shockwave that interrupts their spell casting.');
Skill[1][4][2] = new Array('Stun Hammer','Bash 41 & Exorcism 21','Blunt&#44; 2H Blunt','A powerful blow to the ground that may knock a victim Unconcious.');
Skill[1][4][3] = new Array('Shatter Armor','Bash 50','Blunt&#44; 2H Blunt&#44; Wand','Knocks your opponent&#39;s armor off with a powerful attack&#44; and interrupts their spell casting.');
Skill[1][4][4] = new Array('Shield Break','Bash 61','Axe&#44; Blunt&#44; Wand','Disables use of Shields.');
Skill[1][4][5] = new Array('Subvert','Bash 71','Blunt','Destroys targets with high defense. Higher Defense of target = Higher damage received.');
Skill[1][5][0] = new Array('Deflect','General Lv45','Shield','If you are hit with a charge attack while you are Blocking&#44; you will deflect the damage.');
Skill[1][5][1] = new Array('Strong Stance','Paradin Lv45','Shield','Empowers the Blocking skill to defend against Magic attacks as well.');
Skill[1][5][2] = new Array('Defensive Attack','Paradin Lv50','Shield','????');
Skill[1][5][3] = new Array('Blocking','Defend 8','Shield','Reduces damage by half or lesser.Applicable for any 1-handed weapon while wielding a Shield. Useful against frontal melee attacks. ');
Skill[1][5][4] = new Array('Shield Bash','Defend 12','Shield','Can only be used after Blocking is activated.2-sec window to pushback an attacker (to knock him over?).');
Skill[1][5][5] = new Array('Parapet','Defend 21','None','- Evasion % + Critical hit resistance');
Skill[1][5][6] = new Array('Auto-guard','Defend 26','Shield','Automatically block attacks using your shield (blocking only reduces damage) within duration of skill.');
Skill[1][5][7] = new Array('Shield Charge','Defend 31','Shield','Only usable while you are Blocking. Raise your shield and charge forward&#44; knocking aside enemies that stand in your way.');
Skill[1][5][8] = new Array('Defensive March','Defend 41','Shield','Enables Blocking (stance) while moving at the cost of moving speed.');
Skill[1][5][9] = new Array('Guardian','Defend 54','None','Take all the damage in place of a party member.');
Skill[1][5][10] = new Array('Bore Brunt','General Lv50 & Defend 54','None','Allows you to take damage in place of the targeted party member. This can be used on up to three people at once.');
Skill[1][5][11] = new Array('Eternal Dirge','Defend 61','None','Disables skill usage to all players within area of effect.');
Skill[1][6][0] = new Array('Hawkeye','Archer Lv20','None','Increases attack power while using ranged weapons.');
Skill[1][6][1] = new Array('Quick Step','Provacateur Lv20','None','Whisk in mind&#44; to increase the power around.');
Skill[1][6][2] = new Array('Accelerate','Archer Lv28','None','Boosts moving speed.(need more info on this =3 )');
Skill[1][6][3] = new Array('Third Eye','Provacateur Lv28','None','Increases the Hit rate or physical attack accuracy PT members.');
Skill[1][6][4] = new Array('Treachery','Saboteur Lv45','None','Prevents you from dropping out of Hiding state when you set up a trap while cloaking.');
Skill[1][7][0] = new Array('Rapid Fire','Archer Lv35','Crossbow','? The dart crossbow allow blazing.');
Skill[1][7][1] = new Array('Sniper Nest','Sniper Lv45','Bow&#44; Crowssbow','Greatly increases attack power but movement is disabled.');
Skill[1][7][2] = new Array('Kindling Arrow','Sniper Lv50','Bow','?? Create a field of fire at an area using a fire arrow.');
Skill[1][7][3] = new Array('Watchful Eye','Hunter Lv45','None','Prevents movement&#44; but allows you to spot and attacking Hiding enemies.');
Skill[1][7][4] = new Array('Arrow Fusillade','Hunter Lv50','Crossbow','When using a crossbow&#44; range increases and you are granted the ability to fire twice in a row.');
Skill[1][7][5] = new Array('Flaming Arrow','Shot 8','Bow&#44; Crowssbow','Shoot fire bolts or fire arrows.');
Skill[1][7][6] = new Array('Cobra Arrow','Shot 12','Bow&#44; Crowssbow','Shoot poison bolts or poison arrows that inflict Poison status.');
Skill[1][7][7] = new Array('Arrow Rain','Shot 26','Bow','Aim up to the skies to rain down arrows at a specified Area of Effect (AOE).');
Skill[1][7][8] = new Array('Arrow Storm','Shot 61','Bow','?? We rained a storm of arrows into the target site&#44; continuous damage. The shooting proficiency&#44; to increase the number of consecutive damage. (Up to 3 times) ( angle shot in order to acquire the skills and the level angle shot disappear from the skill list)');
Skill[1][7][9] = new Array('Multi Shot','Shot 41 & Trapping 21','Crossbow','Fire crossbow bolts in five directions at once.');
Skill[1][7][10] = new Array('Charge Shot','Shot 50 & Assassination 21','Bow','Target when hit&#44; gets Knockback status.');
Skill[1][7][11] = new Array('Silence Arrow','Shot 54','Bow&#44; Crowssbow','Silence a victim to disable spell casting.');
Skill[1][7][12] = new Array('Pinning Arrow','Shot 71','Bow&#44; Crowssbow','Chance to render target Immobile. ?? Need more info on this skill.');
Skill[1][8][0] = new Array('Poison Making','Alchemy 8','1x Deadly Nightshade&#44; 1x Empty Bottle','Create a Poison Vial using: 1x Deadly Nightshade&#44; 1x Container.');
Skill[1][8][1] = new Array('Toxify','Alchemy 12','1x Poison Vial','Apply poison attribute on weapon to inflict Poison status. Consumes 1 Poison Vial.');
Skill[1][8][2] = new Array('Serum','Alchemy 26','1x Antidote Herb&#44; 1x Empty Bottle','Create an Antidote Vial using: 1x Antidote Herb&#44; 1x Container.');
Skill[1][8][3] = new Array('Potion Crafting','Alchemy 41','1x Moonlight Herb&#44; 1x Aquilegia&#44; 1x Empty Bottle','Create a Mysterious Potion using: 1x Moonlight Herb&#44; 1x Aquilegia&#44; 1x Container.');
Skill[1][8][4] = new Array('Befuddle','Alchemy 50','1x Poison Vial','Causes more Cast Time Delay to a target if hit while casting. 1x Poison Vial consumed');
Skill[1][8][5] = new Array('Toxic Aura','Alchemy 61','None','Increases Aura Damage while Toxify is active.');
Skill[1][8][6] = new Array('Surveillance','Alchemy 71','None','Enable to spot traps laid by the enemy.');
Skill[1][9][0] = new Array('Hide','Scout Lv18','None','Enables hiding/cloaking on a the spot. *User cannot move while Hiding');
Skill[1][9][1] = new Array('Cloak','Provacateur Lv20','None','Enables movement while in Hidden status.');
Skill[1][9][2] = new Array('Furtive Steps','Assassin Lv45','None','Increases MP regeneration and removes the moving penalty while cloaking.');
Skill[1][9][3] = new Array('Counterpunch','Assassin Lv50','Fist','When using first weapons&#44; you will strike with a weaker follow-up attack.');
Skill[1][9][4] = new Array('Backstab','Assassination 8','Knife&#44; Fist','A strong blow to the enemy is incurred if attacked from behind.');
Skill[1][9][5] = new Array('Dagger Throw','Assassination 12','Knife','Quickly throw daggers at a single target.');
Skill[1][9][6] = new Array('Rush','Assassination 26','Knife&#44; Fist','Attack opponent repeatedly while neglecting your own defense.');
Skill[1][9][7] = new Array('Blindside','Assassination 41','Knife&#44; Fist','Only available while in Hiding state. Hiding state is not removed when attack hits.');
Skill[1][9][8] = new Array('Pierce Armor','Assassination 54','Knife&#44; Fist','A strike that aims for openings in your opponent&#39;s armor. Especially effective for enemies who are Knocked Down.');
Skill[1][9][9] = new Array('Double-Cross','Assassination 71','Knife&#44; Fist','All skills (except this skill) in Cooldown status are reset after striking the enemy in the back.');
Skill[1][10][0] = new Array('Disarm','Trapping 8','None','Defuses all traps within user&#39;s area of effect.');
Skill[1][10][1] = new Array('Tangled Legs','Trapping 16','1x Trap','Trap to render the enemy Immobile. 1x Trap is consumed.');
Skill[1][10][2] = new Array('Plant Mine','Trapping 26','1x Trap','Explosive trap damages surround areas when stepped on. 1x Trap is consumed.');
Skill[1][10][3] = new Array('Worm Bomb','Trapping 41','2x Trap','Unleashes a worm that moves forward in a straight line&#44; exploding whatever it touches. 2x Traps are used.');
Skill[1][10][4] = new Array('Safe Zone','Trapping 50','None','When a players enters the area of effect&#44; any effects on them caused by Field skills will be dispelled.');
Skill[1][10][5] = new Array('Stone Prison','Trapping 61','1x Trap','Locks a player on horseback in a 4-walled area trap when stepped on. 1x Trap used.');
Skill[1][10][6] = new Array('Mind Warp','Trapping 71','1x Trap','Trap that reduces some MP of the victim. 1x Trap used.');
Skill[1][11][0] = new Array('Invigorate','Scout Lv12','None','Increases movement speed.');
Skill[1][11][1] = new Array('Backstep','Techniques 3','None','Step backward to instantly avoid a side or frontal attack. ? Also useful in escaping pursuers.');
Skill[1][11][2] = new Array('Dash','Dodge 8','None','Boost running speed. Best for chasing chickens.');
Skill[1][11][3] = new Array('Quick Step','Dodge 16','None','Increases Evasion ability.');
Skill[1][11][4] = new Array('Tangled Fingers','Dodge 21','None','Reduce an opponent&#39;s physical attack accuracy.');
Skill[1][11][5] = new Array('Reinforce','Dodge 26','None','+15% Knock Down&#44; Knock Out&#44; Freeze Resistance.');
Skill[1][11][6] = new Array('Avoidance','Dodge 41','None','While this skill is in effect&#44; your dodge rate increases. The effects ends when you are hit by two physical attacks.');
Skill[1][11][7] = new Array('Intuition','Dodge 50','None','Enables chance to evade an enemy&#39;s magical attack.');
Skill[1][11][8] = new Array('Bolster','Dodge 66','None','Gives a Dash skill effect to a target player. Temporarily boost a target&#39;s moving speed.');
Skill[1][12][0] = new Array('Meditation','Acolyte Lv12','None','Unifies your spirit and increases the amount regained by Mana (MP) recovery.');
Skill[1][12][1] = new Array('Inspiration','Priest Lv20','None','Increases your spirit through honed senses.');
Skill[1][12][2] = new Array('Blessed Garments','Ascetic Lv20','None','When you wear a equipment that has a Light Aura: + Poison&#44; Charm&#44; Magic Resistance.');
Skill[1][12][3] = new Array('Physical Barrier','Grace 102','None','Raises a barrier that prevents physical attacks against a target.');
Skill[1][12][4] = new Array('Magical Barrier','Grace 102','None','Raises a barrier that prevents magical attacks against a target.');
Skill[1][13][0] = new Array('Heal','Acolyte Lv8','None','Recovers a target&#39;s LP using healing magic.');
Skill[1][13][1] = new Array('Revive','Priest Lv35','None','Resurrects a fallen ally. 3x Holy Water is consumed.');
Skill[1][13][2] = new Array('Sanctuary','Cleric Lv45','None','Creates an area of effect where all players regenerate LP over time.');
Skill[1][13][3] = new Array('Merciful Blessing','Cleric Lv50','None','Increases the power LP recovery spells.');
Skill[1][13][4] = new Array('Karmic Aura','Enchanter Lv50','None','Grants nearby allies the positive effects of blessings.');
Skill[1][13][5] = new Array('First Aid','Banevolence 8','None','Recovers a target&#39;s LP by a small amount.');
Skill[1][13][6] = new Array('Cleanse','Banevolence 12','None','Detoxify a target afflicted with Poison status.');
Skill[1][13][7] = new Array('Regenerate','Banevolence 21','None','Regenerates a target&#39;s LP over time.');
Skill[1][13][8] = new Array('Vivify','Banevolence 26','None','Cures: Sleep&#44; Knock Out&#44; and Freeze status to one target.');
Skill[1][13][9] = new Array('Restoration','Banevolence 41','None','Regenerates LP of all PT members over time.');
Skill[1][13][10] = new Array('Healing Aura','Banevolence 54','None','Recovers LP of all PT members.');
Skill[1][13][11] = new Array('Purify','Banevolence 71','None','Removes all negative status of a target. Also increases resistance against status effects.');
Skill[1][14][0] = new Array('Tranquil Mind','Priest Lv20','None','Increases MP recovery rate of all PT members.');
Skill[1][14][1] = new Array('Divine Aid','Priest Lv28','None','Temporarily increase all PT member&#39;s Max LP.');
Skill[1][14][2] = new Array('Enchantment','Enchanter Lv45','None','Places an effect on a targeted ally player granting them increased Aura Damage and Magic Attack Power.');
Skill[1][14][3] = new Array('Velox','Blessing 8','None','Increases the Attack Speed of a target.');
Skill[1][14][4] = new Array('Lapis Medio','Blessing 12','None','Increases the physical defense of all party members.');
Skill[1][14][5] = new Array('Impedimenta','Blessing 21','None','Reduces an enemy&#39;s moving speed.');
Skill[1][14][6] = new Array('Group Barrier','Blessing 26','None','Reduces damage received by all PT members.');
Skill[1][14][7] = new Array('Aqua Elymus','Blessing 41','1x Empty Bottle','Create one Holy Water using: 1x Empty Bottle');
Skill[1][14][8] = new Array('Saltio','Blessing 54','None','Increases a target&#39;s casting speed.');
Skill[1][14][9] = new Array('Battle Prayer','Blessing 61','None','Target increases in Strength&#44; Agility&#44; and Intelligence stats.');
Skill[1][15][0] = new Array('Mana Restore','Ascetic Lv20','None','Restores the target&#39;s MP (Mana) by invigorating their magical power.');
Skill[1][15][1] = new Array('Speedy Gale','Ascetic Lv28','None','Increases Evasion of all PT members.');
Skill[1][15][2] = new Array('Sound Mind','Monk Lv45','None','Reduces the duration of De-Buff spells or negative status effects inflicted on a player.');
Skill[1][15][3] = new Array('Mana Swap','Exorcist Lv45','None','Swaps MP with an ally&#39;s.');
Skill[1][15][4] = new Array('Soul Swap','Exorcist Lv50','None','Exchanges your status effects to a targets&#39;s');
Skill[1][15][5] = new Array('Mental Aid','Grace 35','None','Dispels a single mental status effects to a target.');
Skill[1][15][6] = new Array('Pure Arrow','Exorcism 8','None','Arrow of light that is effective against Demons and Undead elemental enemies.');
Skill[1][15][7] = new Array('Elemental Absorption','Exorcism 12','None','Fire&#44; Ice&#44; Lightning elemental damage resistance.');
Skill[1][15][8] = new Array('Bless Weapon','Exorcism 26','None','Grants an aura of Light to a target&#39;s weapon.');
Skill[1][15][9] = new Array('Remedium','Exorcism 41','None','Dispels a negative status effect through the power of blessing.');
Skill[1][15][10] = new Array('Holy Rays','Exorcism 54','None','Creates pillars of light surrounding the caster&#44; damaging one&#39;s enemies who come near.');
Skill[1][15][11] = new Array('Banish','Exorcism 61','None','Eliminates all summoned creatures within a certain radius of the caster.');
Skill[1][15][12] = new Array('Devotions','Blessing 20 & Exorcism 61','None','Supplies the MP for any skills used by the target. This can be used to up to 4 people. Up to 4 players can share/use your MP.');
Skill[1][15][13] = new Array('Silent Void','Exorcism 71','None','Disables Field Skills and prevents targeting areas within the area of effect. Disables AOE spell targetting.');
Skill[1][16][0] = new Array('Minstrel&#39;s Song','Hymn 8','None','Song that improves concentration. Increases Accuracy & Evasion to affected players.');
Skill[1][16][1] = new Array('Luminous Chant','Hymn 21','None','Enable use Chant skills while moving. Moving speed depends of Chant skill level.');
Skill[1][16][2] = new Array('Peaceful Hymn','Banevolence 61 & Hymn 30','None','Song that increases defense. Affected players do not suffer damage below a certain amount.');
Skill[1][16][3] = new Array('Sage&#39;s Song','Blessing 71 & Hymn 30','None','Song that increases magic attack power and reduces cool-down time of players within range of effect.');
Skill[1][17][0] = new Array('Scholar','Wizard Lv20','None','Your vast knowledge of the magical arts increases your magical strength.');
Skill[1][17][1] = new Array('Shadow Garments','Sorcerer Lv20','None','When you wear equipment with Dark Aura&#44; you gain: + Fire&#44; Ice&#44; Lightning Resistance');
Skill[1][18][0] = new Array('Fire Bolt','Mage Lv1','None','Inflict magic damage with a flaming arrow.');
Skill[1][18][1] = new Array('Shock','Mage Lv12','None','Lightning strike on the enemy with stun effect.');
Skill[1][18][2] = new Array('Thunder Crash','Wizard Lv20','None','Causes powerful lightning to strike your opponent&#39;s head.');
Skill[1][18][3] = new Array('Magical Aid','Warlock Lv45','None','Further increases magic attack power.');
Skill[1][18][4] = new Array('Hailstone','Elemental 8','None','Launch a mass of ice towards the enemy.');
Skill[1][18][5] = new Array('Thunder Ball','Elemental 12','None','Create a lightning ball which strike the surroundings causing damage to multiple enemies.');
Skill[1][18][6] = new Array('Ice Spear','Elemental 21','None','Shoot the enemy with an ice arrow.');
Skill[1][18][7] = new Array('Fire Storm','Elemental 26','None','Generates a tornado of flame around the caster. AOE spell.');
Skill[1][18][8] = new Array('Resist Fire','Elemental 33','None','+ Ice Resist. - Fire&#44; Lightning Resist.');
Skill[1][18][9] = new Array('Resist Cold','Elemental 33','None','+ Fire Resist. - Ice&#44; Lightning Resist.');
Skill[1][18][10] = new Array('Resist Lightning','Elemental 33','None','+ Lightning Resist. - Fire&#44; Ice Resist.');
Skill[1][18][11] = new Array('Ice Storm','Elemental 54','None','Creates a vortex of cold air that can Knockback foes. AOE spell.');
Skill[1][18][12] = new Array('Ice Tempest','Elemental 71','None','Creates an immense icy vortex that can Knock back foes. AOE spell.');
Skill[1][18][13] = new Array('Time Bomb','Elemental 61','None','Blow up a target after a certain period of time. Attack power is dependent on time elapsed before activation.');
Skill[1][18][14] = new Array('Thunder Storm','Exorcism 40 & Elemental 61','None','Cause thunderstorms at a given point. Targets on horseback will be rendered Immobile. AOE spell.');
Skill[1][18][15] = new Array('Meteor Shower','Elemental 61 & Invocation 40','None','Meteorites fall around a specified point. Those in the area of effect can be Knocked Out. AOE spell.');
Skill[1][19][0] = new Array('Memorize','Conjurer Lv45','None','Registers a location for Teleportation. Can only be used on certain maps.');
Skill[1][19][1] = new Array('Teleport','Conjurer Lv45','None','Creates a warp linking your current location with the location saved by Memorize skill.');
Skill[1][19][2] = new Array('Intelletto','Conjurer Lv50','None','Increases number of locations saved by Memorize Skill based on the Invocation Proficiency level of the user.');
Skill[1][19][3] = new Array('Supreme Mind','Conjurer Lv50','None','Improves your skills by strengthening your mind.');
Skill[1][19][4] = new Array('Soul Blight','Invocation 8','None','Illuminate the caster&#39;s surroundings to dispel the enemy&#39;s invisibility status.');
Skill[1][19][5] = new Array('Mana Shield','Invocation 21','None','Caster&#39;s MP will be taken instead of HP each (physical?) damage suffered. ');
Skill[1][19][6] = new Array('Clear Mind','Invocation 31','None','Reduces probability of cast interruption.');
Skill[1][19][7] = new Array('Psychic Blade','Invocation 41','None','Attack damage depends on opponent&#39;s defense.');
Skill[1][19][8] = new Array('Blockade','Invocation 50','None','Embodies caster in a huge wall that all players cannot pass through.');
Skill[1][19][9] = new Array('Summon Sandman','Invocation 61','None','Summons a giant tornado that inflict damage and can put your opponent to Sleep.');
Skill[1][19][10] = new Array('Malevolent Plant','Invocation 71','None','Summons a plant at a designated point. The plant will begin using ranged attacks on nearby enemies.');
Skill[1][20][0] = new Array('Dark Shield','Shadowblade Lv45','None','Reduces the amount of Rebound damage you take from Dark auras.');
Skill[1][20][1] = new Array('Conceal','Shadowblade Lv50','None','Grants the hiding state to nearby party members.');
Skill[1][20][2] = new Array('Infect','Darkness 8','None','A strike which inject deadly poison into the body. Inflicts Poison status effect to victim.');
Skill[1][20][3] = new Array('Gloom','Darkness 16','None','Casting a dark aura on the weapon. Those injured by the weapon will suffer a curse which will revert back any kind of attack to himself.');
Skill[1][20][4] = new Array('Blood Drain','Darkness 21','None','Extracts your opponent&#39;s HP to add it to your own.');
Skill[1][20][5] = new Array('Mind Venom','Darkness 26','None','Feed poison into a person&#39;s body from a small wound&#44; inflicting Corrosion status effect.');
Skill[1][20][6] = new Array('Dispel','Darkness 33','None','Removes one target&#39;s Positive Status Effect&#44; Enchantment&#44; or Buffs.');
Skill[1][20][7] = new Array('Resist Malice','Darkness 35','None','+ Poison&#44; Dark Resistance. - Charm Resistance.');
Skill[1][20][8] = new Array('Undermine','Darkness 41','None','Amplifies the damage a target will receive.');
Skill[1][20][9] = new Array('Pestilence','Darkness 54','None','Summons forth a malign aura from the ground&#44; causing Poison damage. Rarely causes the Weakness effect.');
Skill[1][20][10] = new Array('Equalize','Darkness 61','None','When you hit with an attack&#44; this skil gives you a chance to remove a Support effect from your target.');
Skill[1][20][11] = new Array('Dark Frenzy','Darkness 71','None','Imbues the powerful aura of darkness to a weapon&#44; causing damage to surrounding enemies.');
Skill[1][21][0] = new Array('Stasis','Corrupter Lv45','None','Stops the duration of negative status effects and reduces the target&#39;s LP recovery rate.');
Skill[1][21][1] = new Array('Leaden Hooves','Corrupter Lv50','None','Reduce a target&#39;s horse running speed using confusing hallucination.');
Skill[1][21][2] = new Array('Enfeeble','Confusion 8','None','Decreases an enemy&#39;s physical attack power.');
Skill[1][21][3] = new Array('Sandstorm','Confusion 12','None','Damage plus added Sleep status effect.');
Skill[1][21][4] = new Array('Psionic Blast','Confusion 21','None','Attack the enemy&#39;s MP points to reduce spell casting capability.');
Skill[1][21][5] = new Array('Weaken','Confusion 26','None','Reduces target&#39;s defense.');
Skill[1][21][6] = new Array('Impede','Confusion 33','None','Slows target&#39;s moving speed and reduces evasion rate.');
Skill[1][21][7] = new Array('Resist Charm','Confusion 35','None','+ Charm Resistance. - Poison&#44; Dark Resistance.');
Skill[1][21][8] = new Array('Icy Strike','Confusion 41','None','Cools the air quickly to inflict Freeze status effect to an enemy.');
Skill[1][21][9] = new Array('Wasteland','Confusion 54','None','Creates a poisonous swamp that prohibits fast movements and poisons the enemies.');
Skill[1][21][10] = new Array('Siren Storm','Confusion 61','None','(AOE) MP damage to enemies within area of effect. May inflict Silence status to victims.');
Skill[1][21][11] = new Array('Cursed Bolt','Confusion 71','None','Has a chance to inflict Curse and Disease on the target and any enemies surrounding them.');
Skill[1][24][0] = new Array('Jousting','Dragoon Lv45','None','Enables normal and skill attacks while mounted on horseback.');
Skill[1][24][1] = new Array('Jousting','Paradin Lv45','None','Enables normal and skill attacks while mounted on horseback.');
Skill[1][24][2] = new Array('Horse Archer','Hunter Lv45','None','Allows usage or certain skills and charge attacks while on horseback.');
Skill[1][24][3] = new Array('Median Riding','Shadowblade Lv45','None','Allows usage of certain skills and charge attacks while on horseback.');
Skill[1][24][4] = new Array('Summon Vehicle','Horsemanship 20','None','Allows you to summon your horse if you are an area suitable for riding.');
Skill[1][24][5] = new Array('Horse Guardian','Horsemanship 31','None','Causes you to absorb attacks targeting your horse.');
Skill[2][0][0] = new Array('激怒','戰士 Lv5','無','挑撥，故意激怒對方攻擊自己');
Skill[2][0][1] = new Array('藥劑專門','戰士 Lv12','無','增加恢復類藥劑使用時的恢復量');
Skill[2][0][2] = new Array('風之迅捷','戰士 Lv18','近身武器、空手','使自己的攻擊速度上升');
Skill[2][0][3] = new Array('提高傷害','角鬥士 Lv20','無','使武器的近戰攻擊力上升 ');
Skill[2][0][4] = new Array('削足','角鬥士 Lv20','近身武器','瞄準對手的腳部進行攻擊，使其移動速度降低。');
Skill[2][0][5] = new Array('信念','騎士 Lv20','無','防止外敵的攻擊，減少自身所受到的傷害');
Skill[2][0][6] = new Array('瘋狂挑釁','騎士 Lv20','無','挑釁，故意使目標對象生氣。暫時將目標注意力集中在自己身上。');
Skill[2][0][7] = new Array('戰爭祈禱','角鬥士 Lv28','無','增加自身以及隊伍成員的攻擊力 ');
Skill[2][0][8] = new Array('天佑','騎士 Lv28','無','提高信仰心，增加隊伍全員的魔法抵抗力');
Skill[2][0][9] = new Array('狂怒攻擊','角鬥士 Lv35','無','犧牲自身防禦，增加自身命中率');
Skill[2][0][10] = new Array('防禦集中','騎士 Lv35','盾牌','只有裝備盾牌時才能使用，犧牲攻擊力，將精神集中於防禦上。');
Skill[2][0][11] = new Array('捨命攻擊','狂戰士 Lv45','無','效果時間內，攻擊力增加，但受到的傷害也增加，攻擊一次後效果消失。');
Skill[2][0][12] = new Array('血之契約','狂戰士 Lv50','無','HP減少30%，換取技能冷卻時間減半的效果');
Skill[2][0][13] = new Array('致殘陷阱','武僧 Lv50','無','從背後命中目標時，敵我雙方停止動作');
Skill[2][0][14] = new Array('順劈','近戰 3','近身武器','很快地猛力一擊，使敵人無法閃避。組合技能的一種');
Skill[2][0][15] = new Array('昏擊','近戰 35','斧、雙手劍、雙手棍、雙手槍','猛力攻擊對手，和擊退一樣給予目標暈眩效果');
Skill[2][0][16] = new Array('匿蹤','近戰 70','無','避開周圍的注意，接觸對自己的鎖定');
Skill[2][0][17] = new Array('堅硬意志','近戰 100','無','效果時間內，免疫擊倒、移動速度減少、定身效果，但攻擊力減半');
Skill[2][1][0] = new Array('二連斬','斬殺 8','單手近身武器','快速斬殺目標二次斬，組合技能之一');
Skill[2][1][1] = new Array('三連斬','斬殺 71','單手近戰武器、雙手劍','迅速斬殺目標三次，有幾率對目標造成流血效果');
Skill[2][1][2] = new Array('迴旋斬','斬殺 12','雙手劍','利用離心力，攻擊自己周圍的敵人');
Skill[2][1][3] = new Array('怒之反擊','斬殺 21','雙手劍、雙手斧、雙手棍、雙手槍、格鬥','接受對手的攻擊，並給以較大的反擊傷害');
Skill[2][1][4] = new Array('瞄準','斬殺 26','無','提高專注度，提升下次攻擊的命中率');
Skill[2][1][5] = new Array('急流','斬殺 41','近身武器','通過強烈的打擊，無視目標防具性能。連續技之一');
Skill[2][1][6] = new Array('劍術大師','斬殺 61','劍、短劍','裝備劍類武器時技能威力提升');
Skill[2][2][0] = new Array('強襲','龍騎士 Lv45','槍','消費精力，發動強大突襲，只能在騎乘中使用');
Skill[2][2][1] = new Array('強突','龍騎士 Lv50','槍','依靠慣性，向前方攻擊，只能在騎乘中使用');
Skill[2][2][2] = new Array('穿刺','突刺 8','槍','用力將槍刺出，攻擊前方直線範圍');
Skill[2][2][3] = new Array('三連刺','突刺 26','槍','連續高速三次刺殺');
Skill[2][2][4] = new Array('回馬槍','突刺 35','無','效果中，自身物理攻擊命中時有一定機率使目標落馬');
Skill[2][2][5] = new Array('投槍','突刺 41','槍','用力將長槍投擲出去，攻擊遠處的敵人');
Skill[2][2][6] = new Array('四連刺','突刺 54','槍','連續高速四次刺殺，三連刺僵硬狀態下使用，增加威力');
Skill[2][2][7] = new Array('反制','突刺 71','槍','對手騎乘狀態時，造成傷害增加，有一定機率使其落馬');
Skill[2][3][0] = new Array('蓄勢','揮砍 8','斧','待機蓄力，發生會心一擊');
Skill[2][3][1] = new Array('反制一擊','揮砍 12','雙手劍、雙手斧、雙手棍、雙手槍、格鬥','化解對手的攻擊，並且反擊');
Skill[2][3][2] = new Array('神聖指引','揮砍 21','斧','通過對聖經的鑽研，使暴擊機率上升');
Skill[2][3][3] = new Array('地裂斬','揮砍 41','斧','用斧切開地面，向自己前方攻擊');
Skill[2][3][4] = new Array('亡命一擊','揮砍 71','斧、鈍器、杖類、雙手劍','給予目標暴力一擊，使其進入暈眩狀態。攻擊失敗或被格擋時自身受到傷害');
Skill[2][4][0] = new Array('碎顱擊','打擊 8','鈍器、杖','通過強力打擊使對手暈眩');
Skill[2][4][1] = new Array('大地衝擊','打擊 26','鈍器、杖','強力擊打地面，給予前方目標傷害，並造成吟唱中斷');
Skill[2][4][2] = new Array('眩暈錘','打擊 41、退魔 21','鈍器','強烈擊打地面，通過強大的地面振動使周圍的敵人暈眩');
Skill[2][4][3] = new Array('破防衝擊','打擊 50','鈍器、杖','用力一擊，解除對象的鎧甲，中斷吟唱');
Skill[2][4][4] = new Array('？？？','打擊 61','斧、鈍器、杖','？？？');
Skill[2][4][5] = new Array('？？？','打擊 71','鈍器、空手','？？？');
Skill[2][5][0] = new Array('棘刺護盾','重裝騎士 Lv45','盾牌','格擋狀態下，受到蓄力攻擊時，反彈傷害');
Skill[2][5][1] = new Array('精神格擋','聖騎士 Lv45','盾牌','格擋姿態時，可以防禦魔法傷害，不會被擊退');
Skill[2][5][2] = new Array('防禦解散','聖騎士 Lv50','盾牌','解除防禦中的行動限制');
Skill[2][5][3] = new Array('格檔','防禦 8','盾牌','迅速舉盾，大幅減少物理傷害');
Skill[2][5][4] = new Array('盾牌重擊','防禦 12','盾牌','只可在格檔姿態中使用，盾防禦同時，給予目標強力反擊');
Skill[2][5][5] = new Array('剛毅護體','防禦 21','無','閃避率下降，但能夠避開緊急情況，不易受到暴擊');
Skill[2][5][6] = new Array('自動警衛','防禦 26','盾牌','熟練用盾進行攻擊，行動中也能夠自動防禦攻擊');
Skill[2][5][7] = new Array('舉盾衝擊','防禦 31','盾牌','只能在格檔中使用。拿著盾往前衝刺，驅散前方的敵人');
Skill[2][5][8] = new Array('防禦','防禦 41','盾牌','可舉盾推進');
Skill[2][5][9] = new Array('替身護衛','防禦 54','無','承受某位隊伍成員所受到的傷害');
Skill[2][5][10] = new Array('犧牲自我','重裝騎士 Lv50、防禦 54','無','承受隊伍成員所受到的傷害，最多3人');
Skill[2][5][11] = new Array('詛咒的聖歌','防禦 61','無','在範圍內的玩家不能使用技能');
Skill[2][6][0] = new Array('鷹眼','弓箭手 Lv20','無','用如同鷹一般銳利的眼四處張望，使命中率上升');
Skill[2][6][1] = new Array('迴避上升','密探 Lv20','無','可以看到敵人快速的動作並且預防，使迴避上升');
Skill[2][6][2] = new Array('風之祝福','弓箭手 Lv28','無','藉由封的祝福，迎著順風，使自身移動速度增加');
Skill[2][6][3] = new Array('提升專注','密探 Lv28','無','使隊伍成員全員命中率增加');
Skill[2][6][4] = new Array('隱密機關','機關師 Lv45','無','障眼法時即使設置了陷阱，也不接觸隱身狀態');
Skill[2][7][0] = new Array('速射','弓箭手 Lv35','十字弩','能夠以快速的動作使弩連射');
Skill[2][7][1] = new Array('精准狙擊','狙擊手 Lv45','弓、十字弩','攻擊力、命中、射程增加，但不可移動。再一次使用後效果消失');
Skill[2][7][2] = new Array('燃油箭','狙擊手 Lv50','弓','用火箭使目標的地點燃燒，形成火系區域');
Skill[2][7][3] = new Array('定時爆彈','狩獵者 Lv45','無','能夠看到視野內隱身狀態的敵人，增加傷害，但不能移動');
Skill[2][7][4] = new Array('風之速射','狩獵者 Lv50','十字弩','使用弩時射程增加，並觸發2連射');
Skill[2][7][5] = new Array('火箭','射擊 8','弓、十字弓','放出火箭');
Skill[2][7][6] = new Array('毒箭','射擊 12','弓、十字弓','放出毒箭，付與目標中毒效果');
Skill[2][7][7] = new Array('箭雨','射擊 26','弓','朝天空放箭，像雨一樣落向目的地區域');
Skill[2][7][8] = new Array('箭之風暴','射擊 61','弓','箭像風暴一樣落到物件地點，造成連續傷害');
Skill[2][7][9] = new Array('多重箭','射擊 41、機關 21','十字弓','能夠同時向5個方向射箭');
Skill[2][7][10] = new Array('擊退箭','射擊 50、暗殺 21','弓','放出擊退目標的強力箭');
Skill[2][7][11] = new Array('沉默之箭','射擊 54','弓、十字弓','使命中的目標變為沉默狀態，以一定機率使目標處於長期沉默');
Skill[2][7][12] = new Array('影襲','射擊 71','弓、十字弩','在目標背後發動攻擊時，施加定身效果，下次攻擊命中後，該效果解除');
Skill[2][8][0] = new Array('毒藥製造','調合 8','巨毒草、空瓶','消耗巨毒草、空瓶，製造毒藥');
Skill[2][8][1] = new Array('塗毒','調合 12','毒藥','消耗毒藥，在武器上塗抹毒藥');
Skill[2][8][2] = new Array('調製解毒劑','調合 26','解毒草、空瓶','消耗解毒草、空瓶，製作解毒劑');
Skill[2][8][3] = new Array('神秘藥','調合 41','月光草、蓬萊花、空瓶','消耗月光草、蓬萊花、空瓶，製作神祕的藥劑');
Skill[2][8][4] = new Array('惡魔語言','調合 50','毒藥','攻擊命中時，對象為吟唱中時，減少吟唱速度，消費1個毒藥');
Skill[2][8][5] = new Array('惡意毒素','調合 61','無','增加涂毒時的屬性傷害');
Skill[2][8][6] = new Array('洞察','調合 71','無','能夠看到敵人設置的陷阱');
Skill[2][9][0] = new Array('隱身','斥侯 Lv18','無','變為隱身狀態，可當場消失');
Skill[2][9][1] = new Array('隱蔽','密探 Lv20','無','進入隱遁狀態，可以直接移動。隱遁狀態將持續消耗MP。');
Skill[2][9][2] = new Array('隱身專精','刺客 Lv45','無','消除障眼法時的移動懲罰，魔力自動恢復');
Skill[2][9][3] = new Array('武器大師','刺客 Lv50','格鬥武器','使用後格鬥武器時，會發動低威力的追加攻擊');
Skill[2][9][4] = new Array('背刺','暗殺 8','短劍、格鬥','對於目標的背後給予強大的一擊');
Skill[2][9][5] = new Array('致命投擲','暗殺 12','短劍','快速向敵人投擲匕首');
Skill[2][9][6] = new Array('鮮血之怒','暗殺 26','短劍、格鬥','不顧防禦，連續攻擊對手');
Skill[2][9][7] = new Array('隱密刺殺','暗殺 41','短劍、格鬥','隱身狀態時可以使用，攻擊命中時不解除隱身狀態');
Skill[2][9][8] = new Array('弱點攻擊','暗殺 54','短劍、格鬥','瞄準鎧甲的間隙突擊，對擊倒的目標有附加傷害效果');
Skill[2][9][9] = new Array('極惡歸返','暗殺 71','無','命中目標的背後時，該技能以外的技能冷卻時間全部解除');
Skill[2][10][0] = new Array('陷阱潰散','機關 8','無','無論敵我，將這一帶設置的陷阱全部解除');
Skill[2][10][1] = new Array('致殘陷阱','機關 16','陷阱','設置一個致殘陷阱，讓對方無法移動。消費1個陷阱');
Skill[2][10][2] = new Array('爆破陷阱','機關 26','陷阱','設置爆炸一整排的爆破陷阱，消費2個陷阱');
Skill[2][10][3] = new Array('連續爆破','機關 41','陷阱x2','設置爆炸一整排的爆破陷阱，消費2個陷阱');
Skill[2][10][4] = new Array('平靜氣氛','機關 50','無','在效果範圍內的玩家，使範圍技能效果失效');
Skill[2][10][5] = new Array('陷馬坑','機關 61','陷阱x4','只對馬產生效果，踏到的玩家周圍的4個方向出現牆壁');
Skill[2][10][6] = new Array('精神干擾','機關 71 ','陷阱','設定一個減少對手MP的陷阱，消費1個陷阱');
Skill[2][11][0] = new Array('疾走','斥侯 Lv12','無','增加自己的移動速度');
Skill[2][11][1] = new Array('遁逃','技巧 3','無','快速地往後退');
Skill[2][11][2] = new Array('突進','閃避 8','無','瞬間提升腳力，能夠高速移動');
Skill[2][11][3] = new Array('快速閃避','閃避 16','無','增加自己的閃避');
Skill[2][11][4] = new Array('擾亂之觸','閃避 21','無','減少目標命中率');
Skill[2][11][5] = new Array('炙熱守護','閃避 26','無','擊倒抗性、暈眩抗性、凍傷抗性+15%');
Skill[2][11][6] = new Array('閃避','閃避 41','無','效果時間中，增加閃避。受到2次物理攻擊後，效果結束');
Skill[2][11][7] = new Array('堅守信仰','閃避 50','無','一定機率閃避敵人的魔法');
Skill[2][11][8] = new Array('疾速賦予','閃避 66','無','對目標施加突進效果');
Skill[2][12][0] = new Array('靜心咒','聖職者 Lv12','無','通過坐下狀態的深刻的精神統一來增加魔力的恢復量');
Skill[2][12][1] = new Array('冥想','牧師 Lv20','無','使感覺靈敏，提升靈感');
Skill[2][12][2] = new Array('虔誠非凡','苦修士 Lv20','無','裝備光屬性裝備後，對於毒系、魅惑、秘法擁有抗性');
Skill[2][12][3] = new Array('守護祈禱','神聖 102','無','賦予目標完全免疫物理攻擊1次 的護盾');
Skill[2][12][4] = new Array('意念祈禱','神聖 102','無','賦予目標完全免疫魔法攻擊1次 的護盾');
Skill[2][13][0] = new Array('治療術','聖職者 Lv18','無','能夠恢復生命的治癒魔法');
Skill[2][13][1] = new Array('復活術','牧師 Lv35','聖水3個','可以讓死亡的目標復活。消耗3個聖水');
Skill[2][13][2] = new Array('聖堂之歌','主教 Lv45','無','能夠使範圍內的全部玩家的HP恢復');
Skill[2][13][3] = new Array('聖母的祝福','主教 Lv50','無','通過強大的慈愛之力，能夠增強HP恢復技能的力量');
Skill[2][13][4] = new Array('聖母之心','吟遊詩人 Lv50','無','使增益效果的祝福技能，效果範圍遍及自己周圍的己方全體人員');
Skill[2][13][5] = new Array('快速治癒','慈愛 8','無','快速恢復目標少量生命值');
Skill[2][13][6] = new Array('解毒術','慈愛 12','無','能夠清除目標毒素');
Skill[2][13][7] = new Array('恢復術','慈愛 21','無','使用治癒的魔法&#44;一定時間內恢復生命');
Skill[2][13][8] = new Array('神聖耳語','慈愛 26','無','能夠治療睡眠&#44;暈眩&#44;凍傷');
Skill[2][13][9] = new Array('自然恢復','慈愛 41','無','能夠使隊伍全體成員的生命恢復&#44;繼續戰鬥');
Skill[2][13][10] = new Array('治療之風','慈愛 54','無','能夠為隊伍全體成員恢復生命的魔法');
Skill[2][13][11] = new Array('天使障壁','慈愛 71','無','完全消除目標異常狀態，並增加異常狀態抵抗力');
Skill[2][14][0] = new Array('精靈的擁抱','牧師 Lv20','無','使隊伍成員全員的魔力恢復速度增加');
Skill[2][14][1] = new Array('自然的祝福','牧師 Lv28','無','藉由祝福生命，使最大生命量大幅增加');
Skill[2][14][2] = new Array('鋼力招來','吟遊詩人 Lv45','無','給效果時間內己方玩家增加屬性傷害和魔法攻擊力');
Skill[2][14][3] = new Array('風之祝福','祝福 8','無','增加目標的攻擊速度');
Skill[2][14][4] = new Array('地之祝福','祝福 12','無','增加隊伍全體成員的防禦力');
Skill[2][14][5] = new Array('殘廢咒','祝福 21','無','減少目標的移動速度');
Skill[2][14][6] = new Array('聖母之守護','祝福 26','無','能夠減少全體隊伍成員受到的傷害');
Skill[2][14][7] = new Array('聖水的祈求','祝福 41','空瓶','消費空瓶&#44;製作聖水');
Skill[2][14][8] = new Array('祝福聖歌','祝福 54','無','施加在友軍身上時&#44;增加技能的吟唱速度');
Skill[2][14][9] = new Array('戰神祝福','祝福 61','無','增加目標的力量，敏捷，智慧');
Skill[2][15][0] = new Array('心靈啟動','苦修士 Lv20','無','使目標或自身的魔力活化，讓MP慢慢的回覆');
Skill[2][15][1] = new Array('閃避結界','苦修士 Lv28','無','增加隊伍全員的閃避率');
Skill[2][15][2] = new Array('淨化屏障','武僧 Lv45','無','使負面傷害的魔法效果時間減少');
Skill[2][15][3] = new Array('心靈轉換','驅魔人 Lv45','無','交換目標玩家和自己的MP值');
Skill[2][15][4] = new Array('身心轉換','驅魔人 Lv50','無','替換自身與目標身上魔法效果的技能');
Skill[2][15][5] = new Array('淨化','神聖 35','無','消除1個負面的魔法效果');
Skill[2][15][6] = new Array('光之箭','退魔 8','無','發出光之箭體，對惡魔和不死族的怪物有加成效果');
Skill[2][15][7] = new Array('元素屏障','退魔 12','無','減少火系、冰系、雷系魔法的傷害');
Skill[2][15][8] = new Array('虔誠賜予','退魔 26','無','使目標的武器帶有光屬性');
Skill[2][15][9] = new Array('淨身術','退魔 41','無','通過祝福&#44;消除負面效果的魔法效果');
Skill[2][15][10] = new Array('天威降臨','退魔 54','無','在自己的周圍出現光之柱&#44;給予傷害');
Skill[2][15][11] = new Array('黑暗回歸','退魔 61','無',' 將範圍內被召喚的東西消滅');
Skill[2][15][12] = new Array('心靈連結','退魔 61、祝福 20','無',' 將目標使用技能時的MP由自己代替，同時可使用4人');
Skill[2][15][13] = new Array('光之赦令','退魔 71','無',' 使作用到一定區域內的範圍技能失效，不能指定地點');
Skill[2][16][0] = new Array('詩人之歌','聖歌 8','無','唱增加命中力的歌，效果內的玩家的命中&閃避增加');
Skill[2][16][1] = new Array('聖歌傳承','聖歌 21','無','使用聖歌技能中，可根據熟練度增加移動速度的效果');
Skill[2][16][2] = new Array('和平之歌','慈愛 61、聖歌 30','無','唱增加防禦力的歌，效果內玩家受到一定量的傷害減免');
Skill[2][16][3] = new Array('魔力之歌','祝福 71、聖歌 30','無','增加效果內的玩家的魔法攻擊力，減少技能冷卻時間');
Skill[2][17][0] = new Array('魔力上升','術士 Lv20','無','獲得豐富多彩的魔法知識，在一定時間內使魔法威力上升');
Skill[2][17][1] = new Array('黑暗結合','巫師 Lv20','無','全身覆蓋黑暗光環，提升對於火焰、冷氣、電擊的抵抗能力');
Skill[2][18][0] = new Array('火之矢','法師 Lv1','無','射出火系箭，造成傷害');
Skill[2][18][1] = new Array('閃電','法師 Lv12','無','從對手的頭上落雷，在一段時間停止移動');
Skill[2][18][2] = new Array('巨雷破','術士 Lv20','無','從對手的頭上落下強力的雷');
Skill[2][18][3] = new Array('精神修養','元素師 Lv45','無','增加自己下次使用的魔法威力');
Skill[2][18][4] = new Array('冰之石','元素 8','無','快速製作冰塊&#44;扔向對象');
Skill[2][18][5] = new Array('雷鳥球','元素 12','無','從遠處扔出一個雷球&#44;對周圍進行傷害');
Skill[2][18][6] = new Array('冰之矛','元素 21','無','快速向對象射出銳利的冰箭');
Skill[2][18][7] = new Array('火之風暴','元素 26','無','在自己的周圍發生火系龍捲風');
Skill[2][18][8] = new Array('火系抗性','元素 33','無','增加對象的火系抵抗&#44;減少冰系抵抗、雷系抵抗');
Skill[2][18][9] = new Array('冰系抗性','元素 35','無','增加對象的冰系抵抗&#44;但減少火系抵抗、雷系抵抗');
Skill[2][18][10] = new Array('雷系抗性','元素 41','無','增加對象的雷系抵抗&#44;但減少火系抵抗、冰系抵抗');
Skill[2][18][11] = new Array('冰之漩渦','元素 54','無','快速在指定區域內生成寒流旋渦&#44;可以擊退被命中的目標');
Skill[2][18][12] = new Array('冰風暴','元素 71','無','生成範圍更大、威力更強的寒流漩渦，可以擊退被命中的目標');
Skill[2][18][13] = new Array('心靈爆震','元素 61','無','使目標在一定時間后爆破，威力與爆破存在的時間有關');
Skill[2][18][14] = new Array('雷電風暴','元素 61、退魔 40','無','在指定地點召喚天雷，目標騎乘狀態下將被定身');
Skill[2][18][15] = new Array('流星風暴','元素 61、具現化 40','無','在指定的地點周圍落下隕石，有暈眩效果');
Skill[2][19][0] = new Array('記憶咒法','德魯伊 Lv45','無','記憶1個地點，只能在部份地圖使用');
Skill[2][19][1] = new Array('移動咒法','德魯伊 Lv45','無','出現一個連結記錄點的特殊傳送門');
Skill[2][19][2] = new Array('長存咒法','德魯伊 Lv50','無','能夠根據熟練度的增加，增加可保存復活點的個數');
Skill[2][19][3] = new Array('精神具現','德魯伊 Lv50','無','通過精神的鍛煉，能夠強化具現系技能');
Skill[2][19][4] = new Array('靈魂之光','具現 8','無','照亮自己的周圍&#44;解除隱身狀態');
Skill[2][19][5] = new Array('魔力屏障','具現 21','無','每次受到攻擊時扣除一定的魔法值來抵消受到的物理傷害。');
Skill[2][19][6] = new Array('風行','具現 31','無','風包圍身體&#44;降低被妨礙吟唱的機率');
Skill[2][19][7] = new Array('虛空之刃','具現 41','無','通過意念射出一把空之刃&#44;目標物理防禦力將會降低傷害');
Skill[2][19][8] = new Array('土牆術','具現 50','無','現出巨大的牆壁。所有玩家都不能通過');
Skill[2][19][9] = new Array('沙之龍','具現 61','無','召喚巨大的龍捲風進行傷害，能夠使對手睡眠');
Skill[2][19][10] = new Array('樹人召喚','具現 71','無','在指定地點召喚樹人，遠距離攻擊靠近的目標');
Skill[2][20][0] = new Array('黑暗吸收','咒術師 Lv45','無','減少暗黑屬性的反動傷害');
Skill[2][20][1] = new Array('偽裝結界','咒術師 Lv50','無','範圍內小隊成員變為隱身狀態');
Skill[2][20][2] = new Array('劇毒孢子','暗黑 8','無','向目標體內送入毒素&#44;使其變為中毒狀態');
Skill[2][20][3] = new Array('黑暗契約','暗黑 16','無','使武器帶有暗黑屬性。每次攻擊自身會受到傷害');
Skill[2][20][4] = new Array('吸血術','暗黑 21','無','吸收對手的生命力&#44;變為自己的');
Skill[2][20][5] = new Array('毒液腐蝕','暗黑 26','無','由傷口向目標體內輸入毒素&#44;使其變為腐蝕狀態');
Skill[2][20][6] = new Array('魔法抹滅','暗黑 33','無','消除對象的強化魔法效果');
Skill[2][20][7] = new Array('毒系抗性','暗黑 35','無','增加對象的毒系抗性、暗系抗性&#44;減少魅惑抗性');
Skill[2][20][8] = new Array('心靈侵害','暗黑 41','無','目標下次受到的傷害大增');
Skill[2][20][9] = new Array('劇毒之源','暗黑 54','無','由大地召喚負面屬性&#44;給予目標毒性傷害。偶爾給與衰弱效果');
Skill[2][20][10] = new Array('削弱心智','暗黑 61','無','進行物理攻擊後，以一定機率消除物件的強化魔法效果');
Skill[2][20][11] = new Array('黑暗狂熱','暗黑 71','無','使武器加上強大的暗黑屬性，攻擊時會出現擴散傷害');
Skill[2][21][0] = new Array('思考凝結','幻術師 Lv45','無','停止負面魔法效果的時間，有減少HP恢復量的效果');
Skill[2][21][1] = new Array('魔法','幻術師 Lv50','無','看到幻覺，使騎手混亂，減少馬的腳力');
Skill[2][21][2] = new Array('迷惑詛咒','咒術 8','無','減少目標的攻擊力');
Skill[2][21][3] = new Array('風沙襲','咒術 12','無','在附近刮起沙的龍捲風&#44;傷害的同時有睡眠效果');
Skill[2][21][4] = new Array('精神制裁','咒術 21','無','對目標精神以直接傷害&#44;減少目標魔力');
Skill[2][21][5] = new Array('毀滅鎧甲','咒術 26','無','減少對象的防禦力');
Skill[2][21][6] = new Array('步伐緩慢','咒術 33','無','減少對象的閃避');
Skill[2][21][7] = new Array('秘法抗性','咒術 35','無','增加目標的魅惑抗性&#44;減少毒系抗性、暗系抗性');
Skill[2][21][8] = new Array('寒冷意念','咒術 41','無','快速將冰系施展在目標上&#44;變為凍傷狀態');
Skill[2][21][9] = new Array('劇毒沼','咒術 54','無','召喚劇毒沼澤&#44;使目標變為中毒狀態、並且移動困難');
Skill[2][21][10] = new Array('靜默風暴','咒術 61','無','傷害範圍內敵人的精神，使對手沉默');
Skill[2][21][11] = new Array('惡念之箭','咒術 71 ','無',' 向目標射出矢，命中敵人後，有一定機率對其周圍的敵人造成詛咒和疾病的效果');
Skill[2][24][0] = new Array('騎乘攻擊','龍騎士 Lv45','無','騎乘時能夠使用騎乘專用技能');
Skill[2][24][1] = new Array('騎乘攻擊','聖騎士 Lv45','無','騎乘時能夠使用騎乘專用技能');
Skill[2][24][2] = new Array('騎乘中射擊','狩獵者 Lv45','無','騎乘時能夠使用騎乘專用技能');
Skill[2][24][3] = new Array('騎手之魂','咒術師 Lv45','無','騎乘時能夠使用騎乘專用技能');
Skill[2][24][4] = new Array('召喚','騎乘 20','無','只要是能夠騎乘的場所，都能召喚馬');
Skill[2][24][5] = new Array('騎士守護','騎乘 31','盾牌','效果中，自身承受坐騎受到的傷害');

